/**
 * PCAN Flash Engine — Real ECU flash execution over CAN bus
 * ==========================================================
 *
 * Executes a FlashPlan against a real ECU through the PCANConnection
 * WebSocket bridge. Sends actual UDS commands, handles seed/key exchange,
 * transfers block data via ISO-TP, and reports progress.
 *
 * This module is the REAL counterpart to the simulator in pcanFlashOrchestrator.
 * It produces the same SimulatorState shape so FlashMissionControl can render
 * both modes identically.
 *
 * PROTOCOL AWARENESS:
 * GM ECUs (E41, E88, E90, etc.) use GMLAN protocol which differs from standard UDS:
 *   - ReadDID uses 0x1A (GMLAN) instead of 0x22 (UDS)
 *   - ProgrammingMode uses 0xA5 (GM-specific)
 *   - ReturnToNormalMode uses 0x20 (GM-specific)
 *   - ReportProgrammedState uses 0xA2 (GM-specific)
 * This engine detects the protocol from the ECU database and adapts accordingly.
 *
 * SAFETY: This module writes to ECU flash memory. Interrupting a flash can
 * brick the ECU. The caller MUST hold a wake lock, prevent navigation, and
 * keep the browser tab alive for the entire duration.
 */

import { PCANConnection, type UDSResponse } from './pcanConnection';
import {
  type FlashPlan, type FlashCommand, type SimulatorState,
  type SimulatorLogEntry, type FlashPhase,
  createSimulatorState, generateRecoveryPlan, formatBytes,
} from '../../../shared/pcanFlashOrchestrator';
import { type ContainerFileHeader, getEcuConfig } from '../../../shared/ecuDatabase';
import { computeGM5B, computeFord3B, getSecurityProfile, hexToBytes as skHexToBytes } from '../../../shared/seedKeyAlgorithms';

// ── Types ──────────────────────────────────────────────────────────────────

export interface FlashEngineCallbacks {
  /** Called on every state change (progress, log, phase, etc.) */
  onStateUpdate: (state: SimulatorState) => void;
  /** Called when flash completes (success, failed, or aborted) */
  onComplete: (result: 'SUCCESS' | 'FAILED' | 'ABORTED') => void;
  /** Called during KEY_CYCLE phase when user action is required.
   *  For KEY_OFF/KEY_ON: must resolve only after user confirms.
   *  For WAIT_BOOT: auto-resolves after waitMs. */
  onUserAction?: (action: { type: import('../../../shared/pcanFlashOrchestrator').UserActionType; prompt: string; autoConfirm: boolean }, waitMs: number) => Promise<void>;
}

export interface FlashEngineConfig {
  /** The PCAN bridge connection (must already be connected) */
  connection: PCANConnection;
  /** The flash plan generated by the orchestrator */
  plan: FlashPlan;
  /** The raw container file as ArrayBuffer */
  containerData: ArrayBuffer;
  /** The parsed container header */
  header: ContainerFileHeader;
  /** Callbacks for progress reporting */
  callbacks: FlashEngineCallbacks;
  /** Dry run mode — executes non-destructive commands only, skips erase/transfer/write */
  dryRun?: boolean;
}

// ── UDS / GMLAN Service IDs ───────────────────────────────────────────────

const UDS = {
  DIAGNOSTIC_SESSION_CONTROL: 0x10,
  ECU_RESET: 0x11,
  CLEAR_DTC: 0x14,
  // GMLAN ClearDiagnosticInformation (GM-specific, uses service 0x04 instead of UDS 0x14)
  CLEAR_DTC_GMLAN: 0x04,
  // GMLAN ReadDataByIdentifier (GM-specific, uses 1-byte DIDs like 0x90, 0xB0, 0xC1)
  READ_DID_GMLAN: 0x1A,
  RETURN_TO_NORMAL: 0x20,
  // UDS ReadDataByIdentifier (standard, uses 2-byte DIDs like 0xF190)
  READ_DID: 0x22,
  SECURITY_ACCESS: 0x27,
  COMMUNICATION_CONTROL: 0x28,
  ROUTINE_CONTROL: 0x31,
  REQUEST_DOWNLOAD: 0x34,
  TRANSFER_DATA: 0x36,
  REQUEST_TRANSFER_EXIT: 0x37,
  TESTER_PRESENT: 0x3E,
  CONTROL_DTC_SETTING: 0x85,
  // GM-specific services
  REPORT_PROGRAMMED_STATE: 0xA2,
  PROGRAMMING_MODE: 0xA5,
  DEVICE_CONTROL: 0xAE,
} as const;

// ── NRC Descriptions ───────────────────────────────────────────────────────

const NRC_NAMES: Record<number, string> = {
  0x10: 'generalReject',
  0x11: 'serviceNotSupported',
  0x12: 'subFunctionNotSupported',
  0x13: 'incorrectMessageLengthOrInvalidFormat',
  0x14: 'responseTooLong',
  0x22: 'conditionsNotCorrect',
  0x24: 'requestSequenceError',
  0x25: 'noResponseFromSubnetComponent',
  0x26: 'failurePreventsExecutionOfRequestedAction',
  0x31: 'requestOutOfRange',
  0x33: 'securityAccessDenied',
  0x35: 'invalidKey',
  0x36: 'exceededNumberOfAttempts',
  0x37: 'requiredTimeDelayNotExpired',
  0x70: 'uploadDownloadNotAccepted',
  0x71: 'transferDataSuspended',
  0x72: 'generalProgrammingFailure',
  0x73: 'wrongBlockSequenceCounter',
  0x78: 'requestCorrectlyReceivedResponsePending',
  0x7E: 'subFunctionNotSupportedInActiveSession',
  0x7F: 'serviceNotSupportedInActiveSession',
};

// GMLAN positive response bytes (service ID + 0x40)
// 0x44 = positive response to ClearDiagnosticInformation (0x04)
// 0x60 = positive response to ReturnToNormal (0x20)
// 0xE2 = positive response to ReportProgrammedState (0xA2)
// 0xE5 = positive response to ProgrammingMode (0xA5)

// ── Flash Engine Class ─────────────────────────────────────────────────────

export class PCANFlashEngine {
  private conn: PCANConnection;
  private plan: FlashPlan;
  private containerData: ArrayBuffer;
  private header: ContainerFileHeader;
  private callbacks: FlashEngineCallbacks;
  private state: SimulatorState;
  private aborted = false;
  private startTime = 0;
  private dryRun: boolean;
  private lastSecurityAccessGranted = false;
  private seedReceivedInPreCheck = false;

  // ECU addressing from the plan's first command
  private txAddr: number;
  private rxAddr: number;

  // Protocol detection: GMLAN vs UDS
  private isGMLAN: boolean;
  private ecuProtocol: string;

  // TesterPresent keepalive — GMLAN uses UUDT format (FE 01 3E on 0x101 every 500ms)
  // UDS uses standard 0x3E 0x80 on physical address every 2s
  private keepaliveTimer: ReturnType<typeof setInterval> | null = null;
  private keepaliveActive = false;
  private keepalivePaused = false; // Paused during active UDS request/response

  /** Destructive UDS services that are skipped in dry run mode */
  private static readonly DESTRUCTIVE_SERVICES = new Set([
    0x31, // RoutineControl (EraseMemory)
    0x34, // RequestDownload
    0x36, // TransferData
    0x37, // RequestTransferExit
  ]);

  constructor(config: FlashEngineConfig) {
    this.conn = config.connection;
    this.plan = config.plan;
    this.containerData = config.containerData;
    this.header = config.header;
    this.callbacks = config.callbacks;
    this.dryRun = config.dryRun ?? false;
    this.state = createSimulatorState(config.plan);

    // Extract CAN addresses from the plan commands
    // Find the physical TX address (skip functional broadcast addresses 0x101, 0x7DF)
    const txCmd = config.plan.commands.find(c => {
      if (!c.canTx) return false;
      const addr = parseInt(c.canTx.split(' ')[0], 16);
      return addr !== 0x101 && addr !== 0x7DF; // Skip functional broadcast
    });
    const rxCmd = config.plan.commands.find(c => c.canRx);
    this.txAddr = txCmd ? parseInt(txCmd.canTx!.split(' ')[0], 16) : 0x7E0;
    this.rxAddr = rxCmd ? parseInt(rxCmd.canRx!.split(' ')[0], 16) : 0x7E8;

    // Detect protocol from ECU database
    const ecuConfig = getEcuConfig(config.plan.ecuType);
    this.ecuProtocol = ecuConfig?.protocol || 'UDS';
    this.isGMLAN = this.ecuProtocol === 'GMLAN';
  }

  /** Abort the flash — sets flag that will be checked between commands */
  abort(): void {
    this.aborted = true;
    this.stopKeepalive();
  }

  // ── TesterPresent Keepalive ──────────────────────────────────────────────

  /**
   * Start sending TesterPresent keepalive.
   * 
   * GMLAN: Uses UUDT format (FE 01 3E) on functional address 0x101 every 500ms.
   *   - FE = UUDT (Unsolicited Unacknowledged Diagnostic Transfer) message type
   *   - 01 = single byte payload length
   *   - 3E = TesterPresent service
   *   - ECU does NOT respond to UUDT messages (fire-and-forget)
   *   - Proven from BUSMASTER logs: 427 frames at ~500ms interval throughout flash
   *
   * UDS: Uses standard 0x3E 0x80 on physical address every 2s.
   *   - 0x80 = suppressPositiveResponse sub-function
   */
  private startKeepalive(): void {
    if (this.keepaliveActive) return;
    this.keepaliveActive = true;

    const isGmlan = this.isGMLAN; // Use pre-computed flag (protocol is 'GMLAN', not 'gmlan')
    const intervalMs = isGmlan ? 500 : 2000;
    const formatDesc = isGmlan ? 'UUDT FE 01 3E on 0x101 every 500ms' : '0x3E 0x80 every 2s';
    this.log('info', this.state.currentPhase, `💓 TesterPresent keepalive started (${formatDesc})`);

    this.keepaliveTimer = setInterval(() => {
      if (!this.keepaliveActive || this.aborted) {
        this.stopKeepalive();
        return;
      }
      // Skip sending if paused (during active UDS request/response).
      if (this.keepalivePaused) return;

      // Fire-and-forget: send TesterPresent.
      // GMLAN: UUDT on 0x101 (functional broadcast, no response expected)
      // UDS: 0x3E 0x80 on physical address (suppressPositiveResponse)
      try {
        const ws = (this.conn as any).ws as WebSocket | null;
        if (ws && ws.readyState === WebSocket.OPEN) {
          const frame = isGmlan
            ? [0xFE, 0x01, 0x3E, 0x00, 0x00, 0x00, 0x00, 0x00]  // GMLAN UUDT format
            : [0x02, 0x3E, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00]; // UDS standard
          const arbId = isGmlan ? 0x101 : this.txAddr;  // GMLAN: functional broadcast
          ws.send(JSON.stringify({
            type: 'can_send',
            id: `tp_keepalive_${Date.now()}`,
            arb_id: arbId,
            data: frame,
          }));
        }
      } catch {
        // Keepalive failure is non-fatal — the next real command will detect connection issues
      }
    }, intervalMs);
  }

  /**
   * Pause keepalive during active UDS request/response exchanges.
   * Some ECUs respond to TesterPresent with NRC even when suppressPositiveResponse
   * is set. These NRC frames can interfere with pending UDS response listeners.
   */
  private pauseKeepalive(): void {
    this.keepalivePaused = true;
  }

  /** Resume keepalive after UDS exchange completes */
  private resumeKeepalive(): void {
    this.keepalivePaused = false;
  }

  /** Stop the TesterPresent keepalive timer */
  private stopKeepalive(): void {
    if (this.keepaliveTimer) {
      clearInterval(this.keepaliveTimer);
      this.keepaliveTimer = null;
    }
    if (this.keepaliveActive) {
      this.keepaliveActive = false;
      this.log('info', this.state.currentPhase, '💓 TesterPresent keepalive stopped');
    }
  }

  // ── Bridge Reconnection ──────────────────────────────────────────────────

  /**
   * Check if the WebSocket connection to the bridge is still open.
   * Uses direct WebSocket readyState check (more reliable than PCANConnection.getState()
   * which may lag behind actual socket state).
   */
  private isWebSocketOpen(): boolean {
    const ws = (this.conn as any).ws as WebSocket | null;
    return ws !== null && ws.readyState === WebSocket.OPEN;
  }

  /**
   * Attempt to reconnect the PCAN bridge if the WebSocket has dropped.
   * This is critical because:
   *   - Bridge may timeout during long PRE_CHECK sequences
   *   - Key cycle (ignition off/on) can cause bridge to lose connection
   *   - Network interruptions can drop the WebSocket
   * 
   * Returns true if bridge is connected (was already open or reconnected successfully).
   */
  private async reconnectBridge(phase: FlashPhase): Promise<boolean> {
    if (this.isWebSocketOpen()) return true;

    this.log('warning', phase, '🔌 Bridge WebSocket disconnected — attempting reconnect...');
    this.state.statusMessage = 'Reconnecting to PCAN bridge...';
    this.emitState();

    // Try up to 3 reconnection attempts with increasing delay
    // Use reconnectForFlash() instead of connect() to avoid full vehicle
    // initialization (VIN read, PID scan) which fails during flash session.
    // reconnectForFlash() also resets UDS monitor state so listeners get re-attached.
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        const reconnected = await this.conn.reconnectForFlash();
        if (reconnected && this.isWebSocketOpen()) {
          this.log('success', phase, `✓ Bridge reconnected (attempt ${attempt}/3)`);
          // Give bridge a moment to stabilize
          await this.delay(500);
          return true;
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        this.log('warning', phase, `Reconnect attempt ${attempt}/3 failed: ${msg}`);
      }
      // Wait before next attempt (1s, 2s, 3s)
      await this.delay(attempt * 1000);
    }

    this.log('error', phase, '❌ Bridge reconnection failed after 3 attempts');
    return false;
  }

  // ── Post-Key-Cycle Session Re-establishment ───────────────────────────────

  /**
   * Re-establish diagnostic session and security access after key cycle.
   * The ECU reboots during key off/on, which drops all active sessions.
   * This method:
   *   1. Waits for ECU to stabilize after boot
   *   2. Re-enters programming session (0x10 0x02 for GMLAN, 0x10 0x03 for UDS)
   *   3. Re-attempts security access using Seed_key.cs AES key
   *   4. Restarts TesterPresent keepalive
   */
  private async reEstablishSession(): Promise<void> {
    this.log('info', 'KEY_CYCLE', '🔄 Re-establishing diagnostic session after key cycle...');
    this.state.statusMessage = 'Re-establishing ECU session after boot...';
    this.emitState();

    // Bridge may have dropped during key cycle — reconnect before attempting session
    const bridgeOk = await this.reconnectBridge('KEY_CYCLE');
    if (!bridgeOk && !this.dryRun) {
      this.log('error', 'KEY_CYCLE', 'Cannot re-establish session — bridge not connected');
      return;
    }

    // Extra settling time — ECU needs time after boot before accepting diagnostic requests
    await this.delay(2000);

    // Step 1: Re-enter diagnostic session
    const maxRetries = 5;
    let sessionOk = false;

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      // Check WebSocket before each attempt — bridge can drop during key-off period
      // Log #14 showed attempts 2-5 all failing with "WebSocket not connected" because
      // the bridge dropped during key-off and wasn't reconnected inside the loop.
      if (!this.isWebSocketOpen()) {
        this.log('info', 'KEY_CYCLE', `Session attempt ${attempt}: WebSocket down, reconnecting...`);
        const ok = await this.reconnectBridge('KEY_CYCLE');
        if (!ok && !this.dryRun) {
          this.log('info', 'KEY_CYCLE', `Session switch attempt ${attempt}: bridge reconnect failed`);
          await this.delay(1500);
          continue;
        }
      }
      try {
        if (this.isGMLAN) {
          // Try programming session (0x10 0x02) — confirmed working from dry runs
          const response = await this.conn.sendUDSRequest(0x10, 0x02, undefined, this.txAddr);
          if (response && response.positiveResponse) {
            this.log('success', 'KEY_CYCLE', `✓ Programming session re-established (attempt ${attempt}/${maxRetries})`);
            sessionOk = true;
            break;
          } else if (response) {
            const nrc = response.nrc ?? 0;
            this.log('info', 'KEY_CYCLE', `Session switch attempt ${attempt}: NRC 0x${nrc.toString(16)} — ECU may still be booting...`);
          } else {
            this.log('info', 'KEY_CYCLE', `Session switch attempt ${attempt}: no response — ECU may still be booting...`);
          }
        } else {
          // Standard UDS: extended session
          const ok = await this.conn.setUDSSession('extended');
          if (ok) {
            this.log('success', 'KEY_CYCLE', `✓ Extended session re-established (attempt ${attempt}/${maxRetries})`);
            sessionOk = true;
            break;
          } else {
            this.log('info', 'KEY_CYCLE', `Session switch attempt ${attempt}: failed — ECU may still be booting...`);
          }
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        this.log('info', 'KEY_CYCLE', `Session switch attempt ${attempt}: ${msg}`);
      }

      // Wait longer between retries — ECU boot can take several seconds
      await this.delay(1500);
    }

    if (!sessionOk) {
      this.log('warning', 'KEY_CYCLE', '⚠️ Could not re-establish session after key cycle — subsequent commands may timeout');
    }

    // Step 2: Re-attempt security access (GMLAN ECUs need this for DID reads)
    // Increased delay from 300ms to 1000ms — dry run #7 showed security access
    // timing out immediately after session re-establishment
    if (this.isGMLAN && sessionOk) {
      await this.delay(1000);
      try {
        // Retry loop for NRC 0x37 (requiredTimeDelayNotExpired) — security lockout after boot
        let seedResp: UDSResponse | null = null;
        for (let lockoutRetry = 0; lockoutRetry < 3; lockoutRetry++) {
          seedResp = await this.conn.sendUDSRequest(0x27, 0x01, undefined, this.txAddr);
          if (seedResp && !seedResp.positiveResponse && (seedResp.nrc === 0x37 || seedResp.nrc === 0x36)) {
            const nrcName = seedResp.nrc === 0x37 ? 'requiredTimeDelayNotExpired' : 'exceededNumberOfAttempts';
            this.log('warning', 'KEY_CYCLE', `NRC 0x${seedResp.nrc.toString(16)} (${nrcName}) — waiting 10s for lockout (retry ${lockoutRetry + 1}/3)`);
            await this.delay(10000);
            continue;
          }
          break;
        }
        if (seedResp && seedResp.positiveResponse) {
          let seedData = seedResp.data || [];
          if (seedData.length > 0 && seedData[0] === 0x01) {
            seedData = seedData.slice(1);
          }
          const seedBytes = new Uint8Array(seedData);
          this.log('info', 'KEY_CYCLE', `Seed received after boot: ${Array.from(seedBytes).map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')}`);

          if (seedBytes.length === 5 && seedBytes.every(b => b === 0)) {
            this.log('success', 'KEY_CYCLE', '🔓 Zero seed — ECU still unlocked after key cycle');
            this.lastSecurityAccessGranted = true;
          } else {
            // ── Check known seed→key lookup table first ──
            const KEYCYCLE_KNOWN_PAIRS: Array<{ seed: number[]; key: number[]; label: string }> = [
              { seed: [0xA0, 0x9A, 0x34, 0x9B, 0x06], key: [0xAF, 0x72, 0x2A, 0x51, 0x7E], label: 'Bench ECU (HPTuners unlocked)' },
              { seed: [0xCE, 0xDA, 0xF9, 0x83, 0x06], key: [0x59, 0x2E, 0xF4, 0x0F, 0x33], label: 'Truck ECU (VOP/PPEI unlocked)' },
            ];
            const kcKnown = KEYCYCLE_KNOWN_PAIRS.find(p =>
              p.seed.length === seedBytes.length && p.seed.every((b, i) => b === seedBytes[i])
            );

            if (kcKnown) {
              const keyBytes = new Uint8Array(kcKnown.key);
              this.log('info', 'KEY_CYCLE', `Known seed matched: ${kcKnown.label}`);
              this.log('info', 'KEY_CYCLE', `Key from lookup: ${Array.from(keyBytes).map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')}`);
              await this.delay(100);
              const keyResp = await this.conn.sendUDSRequest(0x27, 0x02, Array.from(keyBytes), this.txAddr);
              if (keyResp && keyResp.positiveResponse) {
                this.log('success', 'KEY_CYCLE', '🔓 Security re-granted (lookup key)');
                this.lastSecurityAccessGranted = true;
              } else {
                const nrc = keyResp?.nrc ?? 0;
                this.log('warning', 'KEY_CYCLE', `Lookup key rejected after boot: NRC 0x${nrc.toString(16)}`);
                this.lastSecurityAccessGranted = false;
              }
            } else {
            // Key computation: Seed_key.cs hardcoded AES keys ONLY
            const kcEcuType = this.plan.ecuType || this.header.ecu_type || '';
            const kcSecProfile = getSecurityProfile(kcEcuType);
            let kcKeyBytes: Uint8Array | null = null;
            let kcKeySource = '';

            if (kcSecProfile?.aesKeyHex && seedBytes.length === 5 &&
                (kcSecProfile.algorithmType === 'GM_5B_AES' || kcSecProfile.algorithmType === 'GM_DUAL')) {
              const aesKeyBytes = skHexToBytes(kcSecProfile.aesKeyHex);
              kcKeyBytes = await computeGM5B(seedBytes, aesKeyBytes);
              kcKeySource = `${kcSecProfile.ecuType} Seed_key.cs AES`;
            }

            if (kcKeyBytes) {
              this.log('info', 'KEY_CYCLE', `🔑 Key computed (${kcKeySource}): ${Array.from(kcKeyBytes).map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')}`);
              await this.delay(100);
              const keyResp = await this.conn.sendUDSRequest(0x27, 0x02, Array.from(kcKeyBytes), this.txAddr);
              if (keyResp && keyResp.positiveResponse) {
                this.log('success', 'KEY_CYCLE', '🔓 Security access re-granted after key cycle');
                this.lastSecurityAccessGranted = true;
              } else {
                const nrc = keyResp?.nrc ?? 0;
                this.log('warning', 'KEY_CYCLE', `Security re-access denied: NRC 0x${nrc.toString(16)}`);
                this.lastSecurityAccessGranted = false;
              }
            } else if (seedBytes.length === 5) {
              this.log('info', 'KEY_CYCLE', `No Seed_key.cs entry for ${kcEcuType} — sending dummy key`);
              const dummyKey = new Uint8Array(5).fill(0x00);
              await this.delay(100);
              const keyResp = await this.conn.sendUDSRequest(0x27, 0x02, Array.from(dummyKey), this.txAddr);
              if (keyResp && keyResp.positiveResponse) {
                this.log('success', 'KEY_CYCLE', '🔓 Security re-granted with dummy key — ECU is unlocked');
                this.lastSecurityAccessGranted = true;
              } else {
                const nrc = keyResp?.nrc ?? 0;
                this.log('warning', 'KEY_CYCLE', `Dummy key rejected after boot: NRC 0x${nrc.toString(16)}`);
                this.lastSecurityAccessGranted = false;
              }
            } else {
              this.log('warning', 'KEY_CYCLE', `No Seed_key.cs entry for ${kcEcuType} — cannot compute key for post-boot security`);
              this.lastSecurityAccessGranted = false;
            }
            } // end known pair else
          }
        } else if (seedResp) {
          const nrc = seedResp.nrc ?? 0;
          this.log('info', 'KEY_CYCLE', `Post-boot seed request: NRC 0x${nrc.toString(16)} — security may not be required`);
        } else {
          this.log('info', 'KEY_CYCLE', 'Post-boot seed request: no response');
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        this.log('warning', 'KEY_CYCLE', `Post-boot security access error: ${msg}`);
      }
    }

    // Step 3: Restart keepalive now that session is re-established
    this.startKeepalive();
    this.log('info', 'KEY_CYCLE', '✓ Post-key-cycle session re-establishment complete');
  }

  /** Execute the full flash plan */
  async execute(): Promise<'SUCCESS' | 'FAILED' | 'ABORTED'> {
    this.startTime = Date.now();
    this.state.isRunning = true;
    this.emitState();

    try {
      // Step -1: Confirm ignition is ON before starting any CAN communication.
      // ECU must be powered for the bridge to detect it on the bus.
      this.log('info', 'PRE_CHECK', '🔑 Confirm ignition is ON before starting...');
      this.state.statusMessage = 'Confirm ignition is ON';
      this.state.currentPhase = 'PRE_CHECK';
      this.emitState();

      if (this.callbacks.onUserAction) {
        await this.callbacks.onUserAction(
          {
            type: 'KEY_ON_START',
            prompt: this.dryRun
              ? 'Turn ignition ON (key on / engine off) before starting DRY RUN. ECU must be powered for CAN communication.'
              : '⚠️ Turn ignition ON (key on / engine off) before starting FLASH. ECU must be powered. Do NOT start engine.',
            autoConfirm: false,
          },
          0 // No timeout — wait indefinitely for user confirmation
        );
      }
      this.log('success', 'PRE_CHECK', '✓ Ignition ON confirmed — proceeding');

      if (this.aborted) {
        this.state.result = 'ABORTED';
        this.state.isRunning = false;
        this.emitState();
        this.callbacks.onComplete('ABORTED');
        return 'ABORTED';
      }

      // Step 0: Ensure bridge connection is established
      this.log('info', 'PRE_CHECK', 'Connecting to PCAN bridge...');
      this.state.statusMessage = 'Connecting to PCAN bridge...';
      this.emitState();

      const connected = await this.conn.connect();
      if (!connected) {
        this.log('error', 'PRE_CHECK', 'FAILED: Could not connect to PCAN bridge — ensure bridge script is running (python pcan_bridge.py)');
        this.state.result = 'FAILED';
        this.state.statusMessage = 'Could not connect to PCAN bridge';
        this.emitState();
        this.callbacks.onComplete('FAILED');
        return 'FAILED';
      }
      this.log('success', 'PRE_CHECK', '✓ PCAN bridge connected');
      this.log('info', 'PRE_CHECK', `ECU: ${this.plan.ecuName} | Protocol: ${this.ecuProtocol} | TX: 0x${this.txAddr.toString(16).toUpperCase()} | RX: 0x${this.rxAddr.toString(16).toUpperCase()}`);
      if (this.dryRun) {
        this.log('info', 'PRE_CHECK', '🧪 DRY RUN MODE — destructive operations (erase, download, transfer) will be skipped');
      }
      this.emitState();

      // Step 0a.5: Allow ECU to settle after bridge connection.
      // Increased from 1.5s to 3s — dry run #7 showed session/security both
      // timeout on first attempt when ECU hasn't fully initialized after CAN bus start.
      this.log('info', 'PRE_CHECK', 'Waiting for ECU to settle after bridge connect...');
      await this.delay(3000);

      // Step 0b: Set diagnostic session before flash commands.
      // From SPS log analysis: GMLAN ECUs respond to 0x10 0x02 (programming session)
      // even though they also support 0xA5 (ProgrammingMode). Use 0x10 0x02 as primary.
      // Retry up to 3 times with 1.5s backoff — ECU may need multiple attempts after cold start.
      if (this.isGMLAN) {
        this.log('info', 'PRE_CHECK', 'Switching to programming session (0x10 0x02)...');
        this.state.statusMessage = 'Switching to programming session...';
        this.emitState();

        let sessionEstablished = false;
        for (let sessionAttempt = 1; sessionAttempt <= 3 && !sessionEstablished; sessionAttempt++) {
          try {
            const response = await this.conn.sendUDSRequest(0x10, 0x02, undefined, this.txAddr);
            if (response && response.positiveResponse) {
              this.log('success', 'PRE_CHECK', `✓ Programming session active (0x10 0x02) — attempt ${sessionAttempt}/3`);
              sessionEstablished = true;
            } else if (response) {
              const nrc = response.nrc ?? 0;
              const nrcName = NRC_NAMES[nrc] || response.nrcName || 'unknown';
              this.log('info', 'PRE_CHECK', `Programming session attempt ${sessionAttempt}/3: NRC 0x${nrc.toString(16)} (${nrcName})`);
              // On last attempt, try GMLAN ProgrammingMode as fallback
              if (sessionAttempt === 3) {
                this.log('info', 'PRE_CHECK', 'Trying GMLAN ProgrammingMode (0xA5 0x01) as fallback...');
                const gmResp = await this.conn.sendUDSRequest(0xA5, 0x01, undefined, this.txAddr);
                if (gmResp && gmResp.positiveResponse) {
                  this.log('success', 'PRE_CHECK', '✓ GMLAN ProgrammingMode active (0xA5 0x01)');
                  sessionEstablished = true;
                } else {
                  this.log('warning', 'PRE_CHECK', 'GMLAN ProgrammingMode also failed — continuing...');
                }
              }
            } else {
              this.log('info', 'PRE_CHECK', `Programming session attempt ${sessionAttempt}/3: no response`);
            }
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            this.log('info', 'PRE_CHECK', `Programming session attempt ${sessionAttempt}/3: ${msg}`);
          }
          if (!sessionEstablished && sessionAttempt < 3) {
            await this.delay(1500);
          }
        }
        if (!sessionEstablished) {
          this.log('warning', 'PRE_CHECK', 'Could not establish programming session after 3 attempts — continuing (ECU may respond to individual commands)');
        }

        // Step 0b2: Attempt security access — GMLAN ECUs require authenticated session
        // before they respond to ReadDID (0x1A) commands
        this.log('info', 'PRE_CHECK', 'Attempting security access for GMLAN DID reads...');
        this.state.statusMessage = 'Requesting security access...';
        this.emitState();
        try {
          await this.delay(200);
          // Request seed (level 0x01 — confirmed working from dry run log)
          // Retry loop for NRC 0x37 (requiredTimeDelayNotExpired) — security lockout timer
          let seedResp: UDSResponse | null = null;
          for (let lockoutRetry = 0; lockoutRetry < 3; lockoutRetry++) {
            seedResp = await this.conn.sendUDSRequest(0x27, 0x01, undefined, this.txAddr);
            if (seedResp && !seedResp.positiveResponse && (seedResp.nrc === 0x37 || seedResp.nrc === 0x36)) {
              const nrcName = seedResp.nrc === 0x37 ? 'requiredTimeDelayNotExpired' : 'exceededNumberOfAttempts';
              this.log('warning', 'PRE_CHECK', `NRC 0x${seedResp.nrc.toString(16)} (${nrcName}) — waiting 10s for lockout to expire (retry ${lockoutRetry + 1}/3)`);
              await this.delay(10000);
              continue;
            }
            break;
          }
          if (seedResp && seedResp.positiveResponse) {
            // Extract seed bytes (strip sub-function echo if present)
            let seedData = seedResp.data || [];
            if (seedData.length > 0 && seedData[0] === 0x01) {
              seedData = seedData.slice(1);
            }
            const seedBytes = new Uint8Array(seedData);
            this.log('info', 'PRE_CHECK', `Seed received (level 0x01): ${Array.from(seedBytes).map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')} (${seedBytes.length} bytes)`);
            this.seedReceivedInPreCheck = true;

            // ── Check known seed→key lookup table first ──
            const PRECHECK_KNOWN_PAIRS: Array<{ seed: number[]; key: number[]; label: string }> = [
              { seed: [0xA0, 0x9A, 0x34, 0x9B, 0x06], key: [0xAF, 0x72, 0x2A, 0x51, 0x7E], label: 'Bench ECU (HPTuners unlocked)' },
              { seed: [0xCE, 0xDA, 0xF9, 0x83, 0x06], key: [0x59, 0x2E, 0xF4, 0x0F, 0x33], label: 'Truck ECU (VOP/PPEI unlocked)' },
            ];
            const preKnown = PRECHECK_KNOWN_PAIRS.find(p =>
              p.seed.length === seedBytes.length && p.seed.every((b, i) => b === seedBytes[i])
            );

            if (preKnown) {
              // Known seed — use lookup key
              const keyBytes = new Uint8Array(preKnown.key);
              this.log('info', 'PRE_CHECK', `Known seed matched: ${preKnown.label}`);
              this.log('info', 'PRE_CHECK', `Key from lookup: ${Array.from(keyBytes).map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')}`);
              await this.delay(100);
              const keyResp = await this.conn.sendUDSRequest(0x27, 0x02, Array.from(keyBytes), this.txAddr);
              if (keyResp && keyResp.positiveResponse) {
                this.log('success', 'PRE_CHECK', '🔓 Security access granted (lookup key)');
                this.lastSecurityAccessGranted = true;
              } else {
                const nrc = keyResp?.nrc ?? 0;
                this.log('warning', 'PRE_CHECK', `Lookup key rejected: NRC 0x${nrc.toString(16)}`);
              }
            } else {
            // Key computation: Seed_key.cs hardcoded AES keys ONLY
            const preEcuType = this.plan.ecuType || this.header.ecu_type || '';
            const preSecProfile = getSecurityProfile(preEcuType);
            let preKeyBytes: Uint8Array | null = null;
            let preKeySource = '';

            if (preSecProfile?.aesKeyHex && seedBytes.length === 5 &&
                (preSecProfile.algorithmType === 'GM_5B_AES' || preSecProfile.algorithmType === 'GM_DUAL')) {
              const aesKeyBytes = skHexToBytes(preSecProfile.aesKeyHex);
              preKeyBytes = await computeGM5B(seedBytes, aesKeyBytes);
              preKeySource = `${preSecProfile.ecuType} Seed_key.cs AES`;
            }

            if (preKeyBytes) {
              this.log('info', 'PRE_CHECK', `🔑 Key computed (${preKeySource}): ${Array.from(preKeyBytes).map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')}`);
              await this.delay(100);
              const keyResp = await this.conn.sendUDSRequest(0x27, 0x02, Array.from(preKeyBytes), this.txAddr);
              if (keyResp && keyResp.positiveResponse) {
                this.log('success', 'PRE_CHECK', '🔓 Security access granted — GMLAN DIDs should now be readable');
                this.lastSecurityAccessGranted = true;
              } else {
                const nrc = keyResp?.nrc ?? 0;
                this.log('warning', 'PRE_CHECK', `Security access denied: NRC 0x${nrc.toString(16)} — GMLAN DIDs may not respond`);
              }
            } else if (seedBytes.length === 5 && seedBytes.every(b => b === 0)) {
              this.log('success', 'PRE_CHECK', '🔓 Zero seed — ECU is already unlocked (HPTuners/aftermarket)');
              this.lastSecurityAccessGranted = true;
            } else if (seedBytes.length === 5) {
              this.log('warning', 'PRE_CHECK', `No Seed_key.cs entry for ${preEcuType} — sending dummy key for unlocked ECU`);
              const dummyKey = new Uint8Array(5).fill(0x00);
              await this.delay(100);
              const keyResp = await this.conn.sendUDSRequest(0x27, 0x02, Array.from(dummyKey), this.txAddr);
              if (keyResp && keyResp.positiveResponse) {
                this.log('success', 'PRE_CHECK', '🔓 Security access granted with dummy key — ECU is unlocked');
                this.lastSecurityAccessGranted = true;
              } else {
                const nrc = keyResp?.nrc ?? 0;
                this.log('warning', 'PRE_CHECK', `Dummy key rejected: NRC 0x${nrc.toString(16)} — ECU requires real key (check Seed_key.cs)`);
              }
            } else {
              this.log('warning', 'PRE_CHECK', `No Seed_key.cs entry for ${preEcuType} (${seedBytes.length}-byte seed) — GMLAN DIDs may not respond`);
            }
            } // end known pair else
          } else if (seedResp) {
            const nrc = seedResp.nrc ?? 0;
            this.log('info', 'PRE_CHECK', `Security seed request: NRC 0x${nrc.toString(16)} — ECU may not require security for DID reads`);
          } else {
            this.log('info', 'PRE_CHECK', 'Security seed request: no response — continuing without security access');
          }
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          this.log('warning', 'PRE_CHECK', `Security access error: ${msg} — continuing...`);
        }
        await this.delay(200);

        // NOTE: For GMLAN, TesterPresent keepalive is now started EARLY by the
        // TesterPresent UUDT command in SESSION_OPEN (per E88 procedure).
        // The startKeepalive() call in executeCommand detects the FE 01 3E UUDT
        // and starts the cyclic timer. No need to start it here.
        // For safety, start it here only if it hasn't been started yet.
        if (!this.keepaliveActive) {
          this.startKeepalive();
        }
      } else {
        this.log('info', 'PRE_CHECK', 'Switching to extended diagnostic session...');
        this.state.statusMessage = 'Switching to extended diagnostic session...';
        this.emitState();
        try {
          const sessionOk = await this.conn.setUDSSession('extended');
          if (!sessionOk) {
            this.log('warning', 'PRE_CHECK', 'Extended session switch returned false — ECU may not support standard UDS session control. Continuing...');
          } else {
            this.log('success', 'PRE_CHECK', '✓ Extended diagnostic session active');
          }
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          this.log('warning', 'PRE_CHECK', `Extended session switch error: ${msg} — continuing with flash plan...`);
        }
        // Start TesterPresent keepalive after session is established
        this.startKeepalive();
      }
      this.emitState();

      // Step 0c.5: CAN bus termination guidance
      this.log('info', 'PRE_CHECK', '⚡ CAN BUS TIP: Enable 120Ω termination on PCAN adapter for stable communication on bench setups. Without proper termination, ECU may respond intermittently.');

      // Step 0c: ECU communication test (dry run only)
      if (this.dryRun) {
        await this.runDryRunPreCheck();
      }

      // Step 0d: Ensure bridge is still connected before entering command loop.
      // The PRE_CHECK phase can take 60-90s (DID reads, retries, dry run checks),
      // and the bridge WebSocket may timeout during this period.
      // If it dropped, reconnect now before SESSION_OPEN commands fire.
      if (!this.isWebSocketOpen()) {
        this.log('warning', 'PRE_CHECK', 'Bridge WebSocket dropped during pre-check — reconnecting before command loop...');
        const bridgeOk = await this.reconnectBridge('PRE_CHECK');
        if (!bridgeOk && !this.dryRun) {
          this.log('error', 'PRE_CHECK', 'FAILED: Bridge reconnection failed — cannot proceed with flash');
          this.state.result = 'FAILED';
          this.state.statusMessage = 'Bridge disconnected and could not reconnect';
          this.emitState();
          this.callbacks.onComplete('FAILED');
          return 'FAILED';
        }
      }

      for (let i = 0; i < this.plan.commands.length; i++) {
        if (this.aborted) {
          this.log('warning', this.state.currentPhase, 'Flash aborted by user');
          this.state.result = 'ABORTED';
          this.state.statusMessage = 'Flash aborted by user';
          this.emitState();
          this.callbacks.onComplete('ABORTED');
          return 'ABORTED';
        }

        const cmd = this.plan.commands[i];
        this.state.currentCommandIndex = i;
        this.state.currentPhase = cmd.phase;
        this.updateProgress(i);
        this.emitState();

        try {
          if (cmd.blockData) {
            if (this.dryRun) {
              // Skip block transfers in dry run
              const { sectionName, totalBytes } = cmd.blockData;
              this.log('info', cmd.phase, `[DRY RUN] Skipping block transfer: ${sectionName} (${formatBytes(totalBytes)}) — would write ${formatBytes(totalBytes)} to ECU flash`);
              this.state.currentBlock++;
              this.state.statusMessage = `[DRY RUN] Skipped ${sectionName}`;
              this.emitState();
            } else {
              await this.executeBlockTransfer(cmd);
            }
          } else {
            await this.executeCommand(cmd);
          }
        } catch (err) {
          this.stopKeepalive();
          const msg = err instanceof Error ? err.message : String(err);
          this.log('error', cmd.phase, `FAILED: ${cmd.label} — ${msg}`);
          this.state.result = 'FAILED';
          this.state.statusMessage = `Flash failed at: ${cmd.label}`;
          this.state.recoveryPlan = generateRecoveryPlan(0x72, cmd.phase, this.plan.ecuType);
          this.emitState();
          this.callbacks.onComplete('FAILED');
          return 'FAILED';
        }
      }

      // All commands completed successfully
      this.stopKeepalive();
      this.state.result = 'SUCCESS';
      this.state.progress = 100;
      this.state.statusMessage = this.dryRun ? 'Dry run completed — all non-destructive commands passed!' : 'Flash completed successfully!';
      this.log('success', 'CLEANUP', this.dryRun
        ? '✅ DRY RUN COMPLETE — ECU communication verified, seed/key exchange tested, no data written'
        : '✅ All commands executed successfully — ECU flash complete');
      this.emitState();
      this.callbacks.onComplete('SUCCESS');
      return 'SUCCESS';

    } catch (err) {
      this.stopKeepalive();
      const msg = err instanceof Error ? err.message : String(err);
      this.log('error', this.state.currentPhase, `Unexpected error: ${msg}`);
      this.state.result = 'FAILED';
      this.state.statusMessage = `Unexpected error: ${msg}`;
      this.emitState();
      this.callbacks.onComplete('FAILED');
      return 'FAILED';
    }
  }

  // ── Dry Run Pre-Check ─────────────────────────────────────────────────────

  /**
   * Run comprehensive ECU communication tests during dry run.
   * Uses protocol-appropriate commands:
   *   - GMLAN: ReadDID 0x1A with GM DIDs (0x90 VIN, 0xB0 ECU ID, 0xC1 CVN)
   *   - UDS:   ReadDID 0x22 with standard DIDs (0xF190 VIN, 0xF188 SW#, etc.)
   * Any response (positive or NRC) proves the send+listen transport is working.
   */
  private async runDryRunPreCheck(): Promise<void> {
    this.log('info', 'PRE_CHECK', `🧪 Testing ECU communication (${this.isGMLAN ? 'GMLAN' : 'UDS'} protocol)...`);
    this.state.statusMessage = 'Testing ECU communication...';
    this.emitState();

    let gotAnyResponse = false;

    try {
      if (this.isGMLAN) {
        // ── GMLAN Protocol: Use service 0x1A with 1-byte DIDs ──
        // Based on SPS log analysis of 2017 L5P Duramax E41:
        //   TX: 0x7E0 1A 90 → RX: 0x7E8 5A 90 [VIN 17 bytes]
        //   TX: 0x7E0 1A B0 → RX: 0x7E8 5A B0 [ECU ID]
        //   TX: 0x7E0 1A C1 → RX: 0x7E8 5A C1 [CVN 4 bytes]
        const gmlanDIDs: Array<{ did: number; name: string }> = [
          { did: 0xB0, name: 'ECU Hardware ID' },
          { did: 0xC1, name: 'Calibration Verification Number 1' },
          { did: 0x90, name: 'VIN (GMLAN)' },
          { did: 0xA0, name: 'Programming Status' },
        ];

        this.log('info', 'PRE_CHECK', '🔧 Using GMLAN ReadDataByIdentifier (0x1A) — GM protocol detected');

        for (const { did, name } of gmlanDIDs) {
          // Inter-command delay to avoid flooding the ECU bus
          await this.delay(200);
          try {
            const response = await this.conn.sendUDSRequest(
              UDS.READ_DID_GMLAN, did, undefined, this.txAddr
            );

            if (response && response.positiveResponse) {
              gotAnyResponse = true;
              const respData = response.data || [];
              const dataHex = respData.map((b: number) => b.toString(16).padStart(2, '0').toUpperCase()).join(' ');
              this.log('success', 'PRE_CHECK', `✓ GMLAN ${name} (DID 0x${did.toString(16).toUpperCase()}) — ${respData.length} bytes: ${dataHex}`);

              // GMLAN positive response for 0x1A: [DID_echo, ...data]
              // The first byte is the DID echo, actual data starts at byte 1
              const actualData = (respData.length > 0 && respData[0] === did) ? respData.slice(1) : respData;

              if (did === 0x90 && actualData.length >= 17) {
                // Decode VIN from response (after DID echo byte)
                const vinBytes = actualData.slice(0, 17);
                const vin = String.fromCharCode(...vinBytes);
                this.log('success', 'PRE_CHECK', `✓ VIN decoded: ${vin}`);
                this.log('success', 'PRE_CHECK', '✓ Multi-frame response confirmed (>7 bytes) — bridge supports ISO-TP segmentation');
              } else if (did === 0x90 && actualData.length > 0 && actualData.length < 17) {
                // Partial VIN — single frame only captured first few bytes
                const partialVin = String.fromCharCode(...actualData.filter(b => b >= 0x20 && b <= 0x7E));
                this.log('info', 'PRE_CHECK', `Partial VIN: ${partialVin} (${actualData.length}/${17} bytes — bridge may not support multi-frame ISO-TP)`);
              }
            } else if (response) {
              gotAnyResponse = true;
              const nrc = response.nrc ?? 0;
              const nrcName = NRC_NAMES[nrc] || response.nrcName || 'unknown';
              this.log('info', 'PRE_CHECK', `GMLAN ${name} (DID 0x${did.toString(16).toUpperCase()}): NRC 0x${nrc.toString(16)} (${nrcName}) — ECU responded`);
            }
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            this.log('info', 'PRE_CHECK', `GMLAN ${name} (DID 0x${did.toString(16).toUpperCase()}): ${msg}`);
          }
        }

        // Also try UDS ReadDID as fallback — some GM ECUs support both protocols
        // BUT skip if we already got a seed response in PRE_CHECK — the ECU is alive,
        // it just doesn't respond to GMLAN DIDs without security unlock.
        // Log #16 showed this fallback adding ~47s of wasted timeouts.
        if (!gotAnyResponse && !this.lastSecurityAccessGranted) {
          // Only try UDS fallback if we never got ANY response (not even a seed)
          if (!this.seedReceivedInPreCheck) {
            this.log('info', 'PRE_CHECK', 'No GMLAN response — trying UDS ReadDID (0x22) as fallback...');
            gotAnyResponse = await this.tryUDSReadDIDs();
          } else {
            this.log('info', 'PRE_CHECK', 'No GMLAN DID response but seed was received — ECU is alive, skipping UDS fallback (DIDs likely need security unlock)');
            gotAnyResponse = true; // seed response proves ECU is alive
          }
        }

      } else {
        // ── Standard UDS Protocol ──
        gotAnyResponse = await this.tryUDSReadDIDs();
      }

      // Also test TesterPresent regardless of protocol
      // Skip for GMLAN — USDT TesterPresent (0x3E 0x00) always returns NRC 0x12
      // (subFunctionNotSupported). UUDT broadcast is the correct keepalive.
      if (!gotAnyResponse && !this.isGMLAN) {
        this.log('info', 'PRE_CHECK', 'Trying TesterPresent (0x3E 0x00)...');
        try {
          const tpResponse = await this.conn.sendUDSRequest(
            UDS.TESTER_PRESENT, 0x00, undefined, this.txAddr
          );
          if (tpResponse) {
            gotAnyResponse = true;
            if (tpResponse.positiveResponse) {
              this.log('success', 'PRE_CHECK', '✓ TesterPresent — positive response');
            } else {
              const nrc = tpResponse.nrc || 0;
              const nrcName = NRC_NAMES[nrc] || 'unknown';
              this.log('success', 'PRE_CHECK', `✓ TesterPresent — ECU responded with NRC 0x${nrc.toString(16)} (${nrcName}) — communication confirmed`);
            }
          }
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          this.log('info', 'PRE_CHECK', `TesterPresent error: ${msg}`);
        }
      }

      if (gotAnyResponse) {
        this.log('success', 'PRE_CHECK', '✓ ECU communication verified — send+listen transport working');
      } else {
        this.log('warning', 'PRE_CHECK', 'No response from ECU to any command — ECU may not be powered or connected');
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      this.log('warning', 'PRE_CHECK', `ECU communication test error: ${msg} — continuing with dry run...`);
    }
    this.emitState();
  }

  /** Try standard UDS ReadDID (0x22) with common DIDs */
  private async tryUDSReadDIDs(): Promise<boolean> {
    const testDIDs: Array<{ did: number[]; name: string; label: string }> = [
      { did: [0xF1, 0x90], name: 'VIN', label: '0xF190' },
      { did: [0xF1, 0x88], name: 'ECU Software Number', label: '0xF188' },
      { did: [0xF1, 0x95], name: 'ECU Hardware Number', label: '0xF195' },
      { did: [0xF8, 0x06], name: 'Calibration ID', label: '0xF806' },
    ];

    for (const { did, name, label } of testDIDs) {
      try {
        const response = await this.conn.sendUDSRequest(
          UDS.READ_DID, undefined, did, this.txAddr
        );
        if (response && response.positiveResponse) {
          const dataHex = response.data.map((b: number) => b.toString(16).padStart(2, '0').toUpperCase()).join(' ');
          this.log('success', 'PRE_CHECK', `✓ ${name} (${label}) read OK — ${response.data.length} bytes: ${dataHex}`);
          if (response.data.length > 7) {
            this.log('success', 'PRE_CHECK', '✓ Multi-frame response confirmed (>7 bytes) — bridge supports ISO-TP segmentation');
          }
          return true;
        } else if (response) {
          const nrc = response.nrc || 0;
          this.log('info', 'PRE_CHECK', `${name} (${label}): NRC 0x${nrc.toString(16)} (${response.nrcName || 'unknown'}) — ECU responded`);
          return true; // NRC = ECU is communicating
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        this.log('info', 'PRE_CHECK', `${name} (${label}): ${msg}`);
      }
    }
    return false;
  }

  // ── Command Execution ──────────────────────────────────────────────────

  private async executeCommand(cmd: FlashCommand): Promise<void> {
    this.state.statusMessage = `${cmd.label}...`;
    this.emitState();

    // KEY_CYCLE commands that require user action (no CAN TX)
    if (cmd.userAction) {
      const { type, prompt, autoConfirm } = cmd.userAction;
      this.log('info', cmd.phase, `⏳ ${cmd.label}`);
      this.state.statusMessage = prompt;
      this.emitState();

      // Stop keepalive during key off — ECU will power down
      if (type === 'KEY_OFF') {
        this.stopKeepalive();
      }
      
      if (this.callbacks.onUserAction) {
        // The callback must block until user confirms (KEY_OFF/KEY_ON)
        // or auto-resolve after timeout (WAIT_BOOT)
        await this.callbacks.onUserAction(
          { type, prompt, autoConfirm: autoConfirm ?? false },
          cmd.timeoutMs
        );
      } else if (autoConfirm) {
        // No callback provided, auto-wait for boot
        await this.delay(cmd.timeoutMs);
      } else {
        // No callback and requires user action — log warning and wait
        this.log('warning', cmd.phase, `⚠️ User action required but no prompt handler: ${prompt}`);
        await this.delay(cmd.timeoutMs);
      }
      
      this.log('success', cmd.phase, `✓ ${cmd.label} — confirmed`);
      this.state.statusMessage = `${cmd.label} — done`;
      this.emitState();

      // After WAIT_BOOT completes, re-establish diagnostic session and security access.
      // The key cycle causes the ECU to reboot, dropping all sessions. We must
      // re-enter programming session and re-authenticate before any further commands.
      if (type === 'WAIT_BOOT') {
        await this.reEstablishSession();
      }

      return;
    }

    // KEY_CYCLE commands without userAction but also no CAN TX (legacy fallback)
    if (cmd.phase === 'KEY_CYCLE' && !cmd.canTx) {
      this.log('info', cmd.phase, `⏳ ${cmd.label}`);
      await this.delay(cmd.timeoutMs);
      this.log('success', cmd.phase, `✓ ${cmd.label}`);
      this.state.statusMessage = cmd.label;
      this.emitState();
      return;
    }

    // Parse the CAN TX bytes from the command
    if (!cmd.canTx) {
      this.log('info', cmd.phase, `✓ ${cmd.label} (no CAN data)`);
      return;
    }

    const txParts = cmd.canTx.split(' ');
    // txParts[0] = address (e.g., "0x7E0" or "0x101" for functional broadcast)
    const cmdTxAddr = parseInt(txParts[0], 16) || this.txAddr;
    const isFunctionalBroadcast = cmdTxAddr === 0x101 || cmdTxAddr === 0x7DF;
    // Handle 'xx' placeholder bytes (used in Send Key commands before key is computed)
    let rawDataParts = txParts.slice(1);
    
    // GMLAN UUDT detection: if first byte is FE, this is a UUDT message.
    // UUDT format: FE <length> <service> [<sub-function>] [padding]
    // FE = Unsolicited Unacknowledged Diagnostic Transfer — ECU does NOT respond.
    const isUUDT = rawDataParts[0]?.toUpperCase() === 'FE';
    
    // For UUDT messages, the frame is already in the correct format (FE len svc ...)
    // We still need to extract the service ID for logging and routing.
    // For standard UDS, the frame is: PCI_length svc sub ...
    const dataBytes = rawDataParts.map(b => {
      const parsed = parseInt(b, 16);
      return isNaN(parsed) ? 0 : parsed;
    });
    
    // Check if this canTx has placeholder bytes (contains 'xx' or unparseable values)
    const hasPlaceholders = rawDataParts.some(b => isNaN(parseInt(b, 16)));
    
    // Parse UDS service from the frame:
    // UUDT: FE <len> <service> [sub] — skip FE, then len byte, then service
    // Standard: <PCI_len> <service> [sub] — skip PCI, then service
    let serviceId: number;
    let subFunction: number | undefined;
    let additionalData: number[] | undefined;
    
    if (isUUDT) {
      // UUDT: dataBytes = [0xFE, length, service, sub?, ...]
      const uudtLen = dataBytes[1] ?? 0;
      serviceId = dataBytes[2] ?? 0;
      subFunction = uudtLen > 1 ? dataBytes[3] : undefined;
      additionalData = uudtLen > 2 ? dataBytes.slice(4, 2 + uudtLen) : undefined;
    } else {
      // Standard UDS: dataBytes = [PCI_length, service, sub?, ...]
      const pciLength = dataBytes[0]; // PCI length byte
      const udsData = pciLength > 0 ? dataBytes.slice(1, 1 + pciLength) : dataBytes.slice(1);
      serviceId = udsData[0] ?? 0;
      subFunction = udsData.length > 1 ? udsData[1] : undefined;
      additionalData = udsData.length > 2 ? udsData.slice(2) : undefined;
    }
    
    // If canTx has placeholders (e.g., Send Key with 'xx' bytes),
    // check if this is a security access send-key that was already handled
    if (hasPlaceholders && serviceId === UDS.SECURITY_ACCESS && subFunction !== undefined && (subFunction % 2) === 0) {
      if (this.lastSecurityAccessGranted) {
        this.log('info', cmd.phase, `\u2713 ${cmd.label} \u2014 already handled during seed request`);
        this.state.statusMessage = cmd.label;
        this.emitState();
        return;
      }
      // If security wasn't granted and we have placeholder bytes, we can't send this command
      if (this.dryRun) {
        this.log('warning', cmd.phase, `[DRY RUN] ${cmd.label} \u2014 skipped (placeholder bytes, no key computed)`);
        return;
      }
    }

    // Dry run: skip destructive services
    if (this.dryRun && PCANFlashEngine.DESTRUCTIVE_SERVICES.has(serviceId)) {
      const svcName = {
        0x31: 'RoutineControl (EraseMemory)',
        0x34: 'RequestDownload',
        0x36: 'TransferData',
        0x37: 'RequestTransferExit',
      }[serviceId] || `Service 0x${serviceId.toString(16)}`;
      this.log('info', cmd.phase, `[DRY RUN] Skipping ${svcName} — ${cmd.label}`);
      this.state.statusMessage = `[DRY RUN] Skipped ${svcName}`;
      this.emitState();
      return;
    }

    // Apply inter-command delay if specified (extracted from BUSMASTER timing analysis)
    if (cmd.delayBeforeMs && cmd.delayBeforeMs > 0) {
      await this.delay(cmd.delayBeforeMs);
    }

    // Log the TX
    this.log('can_tx', cmd.phase, `TX: ${cmd.canTx}`);

    // UUDT messages (GMLAN functional broadcast): fire-and-forget, no response expected.
    // Send the raw CAN frame directly and return immediately.
    if (isUUDT) {
      // Special handling: if this is a TesterPresent UUDT (FE 01 3E), start the
      // cyclic keepalive timer. Per E88 procedure, TesterPresent cyclic starts
      // EARLY in the SESSION_OPEN sequence (right after ReturnToNormal) and runs
      // continuously throughout the entire flash operation.
      const isTesterPresentUUDT = serviceId === UDS.TESTER_PRESENT;
      if (isTesterPresentUUDT && !this.keepaliveActive) {
        this.startKeepalive();
        this.log('success', cmd.phase, `\u2713 ${cmd.label} — cyclic keepalive started (500ms interval)`);
        this.state.statusMessage = cmd.label;
        this.emitState();
        return;
      }

      try {
        // Check WebSocket and attempt reconnect if needed
        if (!this.isWebSocketOpen()) {
          await this.reconnectBridge(cmd.phase);
        }
        const ws = (this.conn as any).ws as WebSocket | null;
        if (ws && ws.readyState === WebSocket.OPEN) {
          // Build 8-byte CAN frame with padding
          const frame = [...dataBytes];
          while (frame.length < 8) frame.push(0x00);
          ws.send(JSON.stringify({
            type: 'can_send',
            id: `uudt_${Date.now()}`,
            arb_id: cmdTxAddr,
            data: frame.slice(0, 8),
          }));
          this.log('success', cmd.phase, `\u2713 ${cmd.label} (UUDT \u2014 no response expected)`);
        } else {
          this.log('warning', cmd.phase, `${cmd.label} \u2014 WebSocket not open, skipping UUDT`);
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        this.log('warning', cmd.phase, `UUDT send error: ${msg} — continuing...`);
      }
      this.state.statusMessage = cmd.label;
      this.emitState();
      return;
    }

    // Handle specific UDS services (standard request/response)
    let response: UDSResponse | null = null;
    // In dry run mode, reduce retries for post-flash DID reads.
    // These reads take ~18s each with full retries (5s timeout × 3 attempts + backoff).
    // With 9+ DIDs in VERIFICATION, that's 162s+ wasted when ECU won't respond
    // to USDT after SESSION_OPEN broadcast (it only responds after key cycle).
    const isPostFlashDIDRead = (cmd.phase === 'VERIFICATION' || cmd.phase === 'KEY_CYCLE') && !cmd.blockData && !cmd.userAction;
    let retries = (this.dryRun && isPostFlashDIDRead) ? Math.min(cmd.retries, 1) : cmd.retries;
    let lastError = '';

    while (retries >= 0) {
      try {
        // Pause keepalive during UDS exchange to prevent NRC interference.
        // Some ECUs respond to 0x3E 0x80 with NRC (7F 3E 12), and these
        // frames can be captured by the response listener for this command.
        this.pauseKeepalive();

        if (serviceId === UDS.SECURITY_ACCESS && subFunction !== undefined) {
          response = await this.handleSecurityAccess(cmd, subFunction);
        } else if (serviceId === UDS.CLEAR_DTC || serviceId === UDS.CLEAR_DTC_GMLAN) {
          // GMLAN: service 0x04 on functional 0x7DF (per E88 procedure)
          // Standard UDS: service 0x14 on functional 0x7DF
          // The orchestrator now sets the correct address in canTx
          response = await this.conn.sendUDSRequest(serviceId, undefined, additionalData, cmdTxAddr);
        } else if (isFunctionalBroadcast) {
          // Functional broadcast (0x101 or 0x7DF): send on broadcast address
          // Accept any response — multiple ECUs may reply, we just need one positive
          response = await this.conn.sendUDSRequest(serviceId, subFunction, additionalData, cmdTxAddr);
        } else {
          response = await this.conn.sendUDSRequest(serviceId, subFunction, additionalData, this.txAddr);
        }

        // Resume keepalive after response received
        this.resumeKeepalive();

        if (response && response.positiveResponse) {
          const rxHex = (response.data || []).map((b: number) => b.toString(16).padStart(2, '0').toUpperCase()).join(' ');
          this.log('can_rx', cmd.phase, `RX: 0x${this.rxAddr.toString(16).toUpperCase()} ${rxHex}`);
          this.log('success', cmd.phase, `✓ ${cmd.label}`);
          this.state.statusMessage = cmd.label;
          this.emitState();
          return;
        } else if (response) {
          const nrc = response.nrc ?? 0;
          const nrcName = NRC_NAMES[nrc] || response.nrcName || 'unknown';
          
          // NRC 0x78 = requestCorrectlyReceivedResponsePending — wait and retry
          if (nrc === 0x78) {
            this.log('info', cmd.phase, `NRC 0x78 — Response pending, waiting...`);
            await this.delay(2000);
            continue; // Don't decrement retries for 0x78
          }

          // ── NRC Success Logic ──
          // In dry run mode, ANY NRC response proves ECU is communicating.
          // For specific services, certain NRCs are expected and non-fatal:
          //   - TesterPresent NRC 0x12 = sub-function 0x00 not supported (GM L5P behavior)
          //   - DiagnosticSessionControl NRC = session type not supported but ECU is alive
          //   - Any NRC in dry run = ECU responded, communication works
          const isTesterPresent = serviceId === UDS.TESTER_PRESENT;
          const isDiagSession = serviceId === UDS.DIAGNOSTIC_SESSION_CONTROL;
          const isReadDID = serviceId === UDS.READ_DID || serviceId === UDS.READ_DID_GMLAN;
          const isClearDTC = serviceId === UDS.CLEAR_DTC || serviceId === UDS.CLEAR_DTC_GMLAN;
          // Functional broadcast: NRC 0x12 (subFunctionNotSupported) or 0x11 (serviceNotSupported)
          // is expected — some ECUs on the bus don't support the service. Treat as success.
          const isBroadcastNRC = isFunctionalBroadcast && (nrc === 0x12 || nrc === 0x11 || nrc === 0x7E);
          // ClearDTC on functional broadcast: NRC is non-fatal (some ECUs may not support it)
          const isClearDTCBroadcast = isClearDTC && isFunctionalBroadcast;
          const isNonFatalNRC = isTesterPresent || isDiagSession || isReadDID || isBroadcastNRC || isClearDTCBroadcast || this.dryRun;
          
          if (isNonFatalNRC) {
            this.log('success', cmd.phase,
              `✓ ${cmd.label} — ECU responded (NRC 0x${nrc.toString(16)}: ${nrcName}) [svc=0x${serviceId.toString(16)}, dry=${this.dryRun}, proto=${this.ecuProtocol}]`
            );
            this.state.statusMessage = `${cmd.label} (comm OK)`;
            this.emitState();
            return;
          }
          
          lastError = `NRC 0x${nrc.toString(16)} (${nrcName})`;
          this.log('nrc', cmd.phase,
            `NRC 0x${nrc.toString(16)} — ${nrcName} [svc=0x${serviceId.toString(16)}, dry=${this.dryRun}, proto=${this.ecuProtocol}]`,
            nrc
          );
        } else {
          // Check if it's a bridge connection issue vs ECU not responding.
          // Use direct WebSocket check (more reliable than getState() which may lag).
          if (!this.isWebSocketOpen()) {
            lastError = 'PCAN bridge disconnected';
            await this.reconnectBridge(cmd.phase);
          } else {
            lastError = 'No response from ECU';
            this.log('warning', cmd.phase, 'No response from ECU \u2014 retrying...');
          }
        }
      } catch (err) {
        this.resumeKeepalive(); // Ensure keepalive resumes even on error
        lastError = err instanceof Error ? err.message : String(err);
        this.log('warning', cmd.phase, `Error: ${lastError} \u2014 retrying...`);
        // If the error is WebSocket-related, try to reconnect
        if (lastError.includes('WebSocket') || lastError.includes('not connected')) {
          await this.reconnectBridge(cmd.phase);
        }
      }

      retries--;
      if (retries >= 0) {
        // Progressive backoff: 1s, 1.5s, 2s, 2.5s... for bench setups with
        // unstable power/termination. Gives ECU more time to recover.
        const retryDelay = 1000 + (cmd.retries - retries - 1) * 500;
        this.log('info', cmd.phase, `Waiting ${retryDelay}ms before retry ${cmd.retries - retries}/${cmd.retries}...`);
        await this.delay(retryDelay);
      }
    }

    // All retries exhausted
    // In dry run mode, timeouts are non-fatal — log warning but don't throw
    if (this.dryRun) {
      this.log('warning', cmd.phase, `[DRY RUN] ${cmd.label}: ${lastError} — continuing (non-fatal in dry run)`);
      this.state.statusMessage = `[DRY RUN] ${cmd.label} (timeout)`;
      this.emitState();
      return;
    }

    // VERIFICATION and KEY_CYCLE DID reads are informational, not safety-critical.
    // If they timeout, log a warning but don't fail the flash — the ECU has already
    // been programmed successfully at this point. Failing here would leave the user
    // thinking the flash failed when it actually succeeded.
    const isPostFlashRead = (cmd.phase === 'VERIFICATION' || cmd.phase === 'KEY_CYCLE') && !cmd.blockData && !cmd.userAction;
    if (isPostFlashRead) {
      this.log('warning', cmd.phase, `${cmd.label}: ${lastError} — continuing (post-flash read is non-fatal)`);
      this.state.statusMessage = `${cmd.label} (timeout, non-fatal)`;
      this.emitState();
      return;
    }

    throw new Error(`${cmd.label}: ${lastError}`);
  }

  // ── Security Access (Seed/Key) ─────────────────────────────────────────

  private async handleSecurityAccess(cmd: FlashCommand, subFunction: number): Promise<UDSResponse | null> {
    // Sub-function odd = request seed, even = send key
    const isRequestSeed = (subFunction % 2) === 1;

    if (isRequestSeed) {
      // Step 1: Request seed from ECU (with NRC 0x37 lockout retry)
      // NRC 0x37 = requiredTimeDelayNotExpired — ECU has a security lockout timer
      // (typically 10 seconds). We wait and retry up to 3 times.
      let seedResponse: UDSResponse | null = null;
      const maxLockoutRetries = 3;
      for (let lockoutAttempt = 0; lockoutAttempt <= maxLockoutRetries; lockoutAttempt++) {
        seedResponse = await this.conn.sendUDSRequest(
          UDS.SECURITY_ACCESS, subFunction, undefined, this.txAddr
        );

        if (!seedResponse) break; // No response at all

        // Check for NRC 0x37 (requiredTimeDelayNotExpired)
        if (!seedResponse.positiveResponse && seedResponse.nrc === 0x37) {
          if (lockoutAttempt < maxLockoutRetries) {
            this.log('warning', cmd.phase,
              `NRC 0x37 — Security lockout timer active. Waiting 10s before retry ${lockoutAttempt + 1}/${maxLockoutRetries}...`);
            await this.delay(10000); // Wait 10 seconds for lockout to expire
            continue;
          } else {
            this.log('error', cmd.phase, 'NRC 0x37 — Security lockout persists after 3 retries (30s total). ECU may need power cycle.');
            return seedResponse;
          }
        }

        // Check for NRC 0x36 (exceededNumberOfAttempts) — also a lockout condition
        if (!seedResponse.positiveResponse && seedResponse.nrc === 0x36) {
          this.log('warning', cmd.phase,
            'NRC 0x36 — Exceeded number of security attempts. Waiting 10s...');
          await this.delay(10000);
          continue;
        }

        break; // Got a real response (positive or other NRC)
      }

      if (!seedResponse) {
        return seedResponse;
      }

      // The seed response might be misclassified as negative if the parser
      // didn't recognize the positive response byte. Check if we have data
      // that looks like a seed (regardless of positiveResponse flag).
      const seedData = seedResponse.data || [];
      if (!seedResponse.positiveResponse && seedData.length === 0) {
        // Genuinely no data — return the NRC response
        return seedResponse;
      }

      // If response has data, extract seed bytes.
      // For positive response: data = [subFunction, ...seedBytes] (subFunction echo)
      // For GMLAN: data might just be the seed bytes directly
      let rawSeedData = seedData;
      if (seedResponse.positiveResponse && rawSeedData.length > 0 && rawSeedData[0] === subFunction) {
        // Strip the sub-function echo byte
        rawSeedData = rawSeedData.slice(1);
      }

      if (rawSeedData.length === 0) {
        if (this.dryRun) {
          this.log('warning', cmd.phase, '[DRY RUN] Seed response has no data — skipping key computation');
          return seedResponse;
        }
        return seedResponse;
      }

      const seedBytes = new Uint8Array(rawSeedData);
      this.log('info', cmd.phase, `Seed received: ${Array.from(seedBytes).map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')} (${seedBytes.length} bytes)`);

      // Step 2: Compute key from seed
      let keyBytes: Uint8Array;

      // ── Known seed→key lookup table (unlocked ECUs with static seeds) ──
      const KNOWN_SEED_KEY_PAIRS: Array<{ seed: number[]; key: number[]; label: string }> = [
        { seed: [0xA0, 0x9A, 0x34, 0x9B, 0x06], key: [0xAF, 0x72, 0x2A, 0x51, 0x7E], label: 'Bench ECU (HPTuners unlocked)' },
        { seed: [0xCE, 0xDA, 0xF9, 0x83, 0x06], key: [0x59, 0x2E, 0xF4, 0x0F, 0x33], label: 'Truck ECU (VOP/PPEI unlocked)' },
      ];

      const knownPair = KNOWN_SEED_KEY_PAIRS.find(p =>
        p.seed.length === seedBytes.length && p.seed.every((b, i) => b === seedBytes[i])
      );

      if (knownPair) {
        keyBytes = new Uint8Array(knownPair.key);
        this.log('info', cmd.phase, `Known seed matched: ${knownPair.label}`);
        this.log('info', cmd.phase, `Key from lookup table: ${Array.from(keyBytes).map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')}`);
      } else {

      // ── Key computation: Seed_key.cs hardcoded AES keys ONLY ──
      const ecuType = this.plan.ecuType || this.header.ecu_type || '';
      const secProfile = getSecurityProfile(ecuType);

      if (secProfile?.aesKeyHex && seedBytes.length === 5 &&
          (secProfile.algorithmType === 'GM_5B_AES' || secProfile.algorithmType === 'GM_DUAL')) {
        // Compute key using hardcoded AES key from Seed_key.cs
        const aesKeyBytes = skHexToBytes(secProfile.aesKeyHex);
        keyBytes = await computeGM5B(seedBytes, aesKeyBytes);
        this.log('info', cmd.phase, `🔑 Key computed (${secProfile.ecuType} Seed_key.cs AES): ${Array.from(keyBytes).map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')}`);
      } else if (secProfile?.algorithmType === 'FORD_3B' && seedBytes.length === 3 && secProfile.aesKeyHex) {
        // Ford 3-byte LFSR from security profile
        const secretBytes = skHexToBytes(secProfile.aesKeyHex);
        keyBytes = computeFord3B(seedBytes, secretBytes);
        this.log('info', cmd.phase, `🔑 Key computed (${secProfile.ecuType} Ford_3B): ${Array.from(keyBytes).map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')}`);
      } else if (seedBytes.length === 5 && seedBytes.every(b => b === 0)) {
        // Zero seed — ECU is already unlocked
        this.log('success', cmd.phase, '🔓 Zero seed — ECU is already unlocked');
        keyBytes = new Uint8Array(5).fill(0x00);
      } else if (seedBytes.length === 5) {
        // No hardcoded key for this ECU — try dummy key for unlocked ECUs
        this.log('warning', cmd.phase, `No Seed_key.cs entry for ${ecuType} — trying dummy key (unlocked ECU only)`);
        keyBytes = new Uint8Array(5).fill(0x00);
      } else {
        if (this.dryRun) {
          this.log('warning', cmd.phase, `[DRY RUN] No Seed_key.cs entry for ${ecuType} (${seedBytes.length}-byte seed) — skipping`);
          return seedResponse;
        }
        throw new Error(`No Seed_key.cs entry for ${ecuType}. Cannot compute key for ${seedBytes.length}-byte seed.`);
      }
      } // end lookup vs compute

      // Step 3: Send key to ECU (sub-function + 1)
      const keyResponse = await this.conn.sendUDSRequest(
        UDS.SECURITY_ACCESS, subFunction + 1, Array.from(keyBytes), this.txAddr
      );

      if (keyResponse && keyResponse.positiveResponse) {
        this.log('success', cmd.phase, '🔓 Security access granted');
        this.lastSecurityAccessGranted = true;
      } else {
        this.lastSecurityAccessGranted = false;
      }

      return keyResponse;
    }

    // This is a send-key command (even sub-function). The seed handler above
    // already sent the key when it processed the preceding seed request.
    // Return a synthetic success to avoid sending a bare key-send with no data.
    if (this.lastSecurityAccessGranted) {
      this.log('info', cmd.phase, '✓ Send Key — already handled during seed request');
      return {
        service: UDS.SECURITY_ACCESS,
        serviceName: 'SecurityAccess',
        subFunction,
        data: [subFunction],
        positiveResponse: true,
        isFlashRelated: true,
        timestamp: Date.now(),
      };
    }

    // If we get here, the seed handler didn't send the key (e.g., dry run with no key available).
    // In dry run mode, return a synthetic response to avoid crashing.
    if (this.dryRun) {
      this.log('warning', cmd.phase, '[DRY RUN] Send Key skipped — no key was computed during seed phase');
      return {
        service: UDS.SECURITY_ACCESS,
        serviceName: 'SecurityAccess',
        subFunction,
        data: [],
        positiveResponse: false,
        nrc: 0x35,
        nrcName: 'invalidKey',
        isFlashRelated: true,
        timestamp: Date.now(),
      };
    }

    // Live mode: try sending the key command (shouldn't normally reach here)
    return await this.conn.sendUDSRequest(UDS.SECURITY_ACCESS, subFunction, undefined, this.txAddr);
  }

  // ── Block Transfer ─────────────────────────────────────────────────────

  private async executeBlockTransfer(cmd: FlashCommand): Promise<void> {
    if (!cmd.blockData) throw new Error('No block data in transfer command');

    const { blockId, sectionName, totalBytes, startAddr, compressed } = cmd.blockData;
    this.state.currentSectionName = sectionName;
    this.state.statusMessage = `Flashing ${sectionName}...`;
    this.emitState();

    // Find the block in the container header
    const block = this.header.block_struct.find(b => b.block_id === blockId);
    if (!block) throw new Error(`Block #${blockId} not found in container`);

    // Get transfer size from block or header
    const xferSize = parseInt(block.xferSize || this.header.xferSize || 'FF8', 16);

    // Calculate block data offset in the container file
    const headerLength = parseInt(this.header.header_length || '3000', 16);
    let blockOffset = headerLength;
    
    // Sum up previous blocks' sizes to find this block's offset
    for (const b of this.header.block_struct) {
      if (b.block_id === blockId) break;
      const bLen = parseInt(b.block_length || '0', 16);
      blockOffset += bLen;
    }

    const blockLength = parseInt(block.block_length || '0', 16) || totalBytes;

    this.log('info', cmd.phase, `Block #${blockId} (${sectionName}): ${formatBytes(blockLength)} @ offset 0x${blockOffset.toString(16).toUpperCase()}`);
    this.log('info', cmd.phase, `Transfer size: 0x${xferSize.toString(16).toUpperCase()} (${xferSize} bytes), Start addr: ${startAddr}`);

    // Step 1: RequestDownload (0x34)
    const rc34 = block.rc34;
    if (rc34) {
      const rc34Bytes = hexToBytes(rc34);
      this.log('can_tx', cmd.phase, `TX: RequestDownload (0x34) — ${rc34}`);
      const dlResponse = await this.conn.sendUDSRequest(UDS.REQUEST_DOWNLOAD, undefined, Array.from(rc34Bytes), this.txAddr);
      
      if (!dlResponse || !dlResponse.positiveResponse) {
        const nrc = dlResponse?.nrc || 0;
        // NRC 0x78 = responsePending — wait and retry (confirmed from SPS log: ECU sends 0x78 then 0x74)
        if (nrc === 0x78) {
          this.log('info', cmd.phase, 'NRC 0x78 — ECU processing RequestDownload, waiting...');
          await this.delay(3000);
          // Retry once
          const retryResponse = await this.conn.sendUDSRequest(UDS.REQUEST_DOWNLOAD, undefined, Array.from(rc34Bytes), this.txAddr);
          if (!retryResponse || !retryResponse.positiveResponse) {
            throw new Error(`RequestDownload failed after retry: NRC 0x${(retryResponse?.nrc || 0).toString(16)} (${NRC_NAMES[retryResponse?.nrc || 0] || 'unknown'})`);
          }
        } else {
          throw new Error(`RequestDownload failed: NRC 0x${nrc.toString(16)} (${NRC_NAMES[nrc] || 'unknown'})`);
        }
      }
      this.log('can_rx', cmd.phase, `RX: RequestDownload accepted`);
    }

    // Step 2: TransferData (0x36) — send block data in chunks
    const blockData = new Uint8Array(this.containerData, blockOffset, Math.min(blockLength, this.containerData.byteLength - blockOffset));
    let bytesSent = 0;
    let sequenceCounter = 1; // Block sequence counter starts at 1

    while (bytesSent < blockData.length) {
      if (this.aborted) throw new Error('Aborted by user');

      const chunkSize = Math.min(xferSize, blockData.length - bytesSent);
      const chunk = blockData.slice(bytesSent, bytesSent + chunkSize);

      // Build TransferData payload: [sequenceCounter, ...data]
      const payload = new Uint8Array(1 + chunk.length);
      payload[0] = sequenceCounter & 0xFF;
      payload.set(chunk, 1);

      // Send via UDS
      const tdResponse = await this.conn.sendUDSRequest(
        UDS.TRANSFER_DATA, undefined, Array.from(payload), this.txAddr
      );

      if (!tdResponse || !tdResponse.positiveResponse) {
        const nrc = tdResponse?.nrc || 0;
        // NRC 0x78 = pending — wait and retry (SPS log shows multiple 0x78 before 0x76)
        if (nrc === 0x78) {
          this.log('info', cmd.phase, 'NRC 0x78 — ECU processing transfer, waiting...');
          await this.delay(2000);
          continue; // Retry same chunk
        }
        throw new Error(`TransferData failed at seq ${sequenceCounter}: NRC 0x${nrc.toString(16)} (${NRC_NAMES[nrc] || 'unknown'})`);
      }

      bytesSent += chunkSize;
      sequenceCounter = (sequenceCounter + 1) & 0xFF; // Wrap at 255

      // Update progress
      this.state.blockProgress = (bytesSent / blockData.length) * 100;
      this.state.transferredBytes = Math.min(
        this.state.transferredBytes + chunkSize,
        this.state.totalBytes,
      );
      this.updateProgress(this.state.currentCommandIndex);
      
      // Log every ~10%
      const prevPct = Math.floor(((bytesSent - chunkSize) / blockData.length) * 10);
      const currPct = Math.floor((bytesSent / blockData.length) * 10);
      if (currPct > prevPct) {
        this.log('can_tx', cmd.phase,
          `TX: 0x${this.txAddr.toString(16).toUpperCase()} 36 ${(sequenceCounter - 1 & 0xFF).toString(16).padStart(2, '0').toUpperCase()} [${chunkSize} bytes] → ${sectionName} (${(this.state.blockProgress).toFixed(0)}%)`,
          blockId
        );
      }

      this.state.statusMessage = `Flashing ${sectionName} — ${this.state.blockProgress.toFixed(0)}%`;
      this.emitState();
    }

    // Step 3: RequestTransferExit (0x37) — only if ECU supports it
    // SPS log shows L5P does NOT use TransferExit (usesTransferExit: false in ECU database)
    const ecuConfig = getEcuConfig(this.plan.ecuType);
    if (ecuConfig?.usesTransferExit !== false) {
      this.log('can_tx', cmd.phase, `TX: RequestTransferExit (0x37)`);
      const exitResponse = await this.conn.sendUDSRequest(UDS.REQUEST_TRANSFER_EXIT, undefined, undefined, this.txAddr);
      
      if (!exitResponse || !exitResponse.positiveResponse) {
        const nrc = exitResponse?.nrc || 0;
        // Some ECUs don't support 0x37 — log warning but don't fail
        if (nrc === 0x11) {
          this.log('warning', cmd.phase, 'RequestTransferExit not supported — continuing');
        } else {
          throw new Error(`RequestTransferExit failed: NRC 0x${nrc.toString(16)} (${NRC_NAMES[nrc] || 'unknown'})`);
        }
      } else {
        this.log('can_rx', cmd.phase, `RX: TransferExit accepted`);
      }
    } else {
      this.log('info', cmd.phase, `Skipping RequestTransferExit (ECU ${this.plan.ecuType} does not use 0x37)`);
    }

    // Block complete
    this.state.currentBlock++;
    this.state.blockProgress = 0;
    this.log('success', cmd.phase,
      `✓ Block #${blockId} (${sectionName}) transferred — ${formatBytes(blockData.length)}`,
      blockId
    );
    this.emitState();
  }

  // ── Progress Calculation ───────────────────────────────────────────────

  private updateProgress(currentIndex: number): void {
    const totalEstMs = this.plan.estimatedTimeMs || 1;
    const PHASE_DELAY: Record<string, number> = {
      PRE_CHECK: 1500, VOLTAGE_INIT: 2000, SESSION_OPEN: 2500,
      SECURITY_ACCESS: 3000, PRE_FLASH: 8000, POST_FLASH: 4000,
      VERIFICATION: 3000, KEY_CYCLE: 10000, CLEANUP: 2000,
    };

    let completedMs = 0;
    for (let i = 0; i < currentIndex; i++) {
      const c = this.plan.commands[i];
      if (c?.blockData) {
        completedMs += (c.blockData.totalBytes / 4000) * 1000;
      } else if (c) {
        completedMs += PHASE_DELAY[c.phase] || 1500;
      }
    }

    // Add partial progress for current block transfer
    const cmd = this.plan.commands[currentIndex];
    if (cmd?.blockData && this.state.blockProgress > 0) {
      const blockTimeMs = (cmd.blockData.totalBytes / 4000) * 1000;
      completedMs += blockTimeMs * (this.state.blockProgress / 100);
    }

    this.state.progress = Math.min((completedMs / totalEstMs) * 100, 99.9);
    this.state.estimatedRemainingMs = Math.max(totalEstMs - completedMs, 0);
    this.state.elapsedMs = Date.now() - this.startTime;
  }

  // ── Helpers ────────────────────────────────────────────────────────────

  private log(type: SimulatorLogEntry['type'], phase: FlashPhase, message: string, blockIdOrNrc?: number): void {
    const entry: SimulatorLogEntry = {
      timestamp: Date.now() - this.startTime,
      phase,
      type,
      message,
    };
    if (type === 'nrc' && blockIdOrNrc !== undefined) entry.nrcCode = blockIdOrNrc;
    if ((type === 'can_tx' || type === 'can_rx') && blockIdOrNrc !== undefined) entry.blockId = blockIdOrNrc;
    this.state.log.push(entry);
  }

  private emitState(): void {
    // Clone state for React immutability
    this.callbacks.onStateUpdate({ ...this.state, log: [...this.state.log] });
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}

// ── Utility Functions ──────────────────────────────────────────────────────

function hexToBytes(hex: string): Uint8Array {
  // Handle various hex formats: "AABBCC", "AA BB CC", "0xAA 0xBB"
  const clean = hex.replace(/0x/gi, '').replace(/\s+/g, '');
  const bytes = new Uint8Array(clean.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(clean.substr(i * 2, 2), 16);
  }
  return bytes;
}

function arraysEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}
