import { z } from 'zod';
import { protectedProcedure, router } from '../_core/trpc';
import { tuneFolders, savedTunes } from '../../drizzle/schema_projects';
import { eq, and, isNull, desc, asc, like, or } from 'drizzle-orm';
import { v4 as uuidv4 } from 'uuid';
import { getDb } from '../db';
import { secureUpload } from '../lib/secureFileAccess';

export const tunesRouter = router({
  // ==================== FOLDERS ====================

  // List folders for a user (optionally filtered by parent)
  listFolders: protectedProcedure
    .input(z.object({
      parentId: z.string().nullable().default(null),
    }))
    .query(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      const conditions = [eq(tuneFolders.userId, ctx.user.id)];
      if (input.parentId) {
        conditions.push(eq(tuneFolders.parentId, input.parentId));
      } else {
        conditions.push(isNull(tuneFolders.parentId));
      }

      const folders = await db.select().from(tuneFolders)
        .where(and(...conditions))
        .orderBy(asc(tuneFolders.sortOrder), asc(tuneFolders.name));

      return folders;
    }),

  // Get full folder tree (all folders for user)
  getFolderTree: protectedProcedure
    .query(async ({ ctx }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      const allFolders = await db.select().from(tuneFolders)
        .where(eq(tuneFolders.userId, ctx.user.id))
        .orderBy(asc(tuneFolders.sortOrder), asc(tuneFolders.name));

      return allFolders;
    }),

  // Create folder
  createFolder: protectedProcedure
    .input(z.object({
      name: z.string().min(1).max(255),
      parentId: z.string().nullable().default(null),
      folderType: z.enum(['root', 'make', 'model', 'year', 'ecu_family', 'ecu_variant', 'custom']).default('custom'),
      vehicleMake: z.string().optional(),
      vehicleModel: z.string().optional(),
      vehicleYear: z.number().optional(),
      ecuFamily: z.string().optional(),
      ecuVariant: z.string().optional(),
      osVersion: z.string().optional(),
      ecuPartNumber: z.string().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      const folderId = uuidv4();

      await db.insert(tuneFolders).values({
        id: folderId,
        userId: ctx.user.id,
        parentId: input.parentId,
        name: input.name,
        folderType: input.folderType,
        vehicleMake: input.vehicleMake,
        vehicleModel: input.vehicleModel,
        vehicleYear: input.vehicleYear,
        ecuFamily: input.ecuFamily,
        ecuVariant: input.ecuVariant,
        osVersion: input.osVersion,
        ecuPartNumber: input.ecuPartNumber,
        isAutoGenerated: false,
      });

      return { id: folderId };
    }),

  // Rename folder
  renameFolder: protectedProcedure
    .input(z.object({
      folderId: z.string(),
      name: z.string().min(1).max(255),
    }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      await db.update(tuneFolders)
        .set({ name: input.name })
        .where(and(
          eq(tuneFolders.id, input.folderId),
          eq(tuneFolders.userId, ctx.user.id),
        ));

      return { success: true };
    }),

  // Move folder
  moveFolder: protectedProcedure
    .input(z.object({
      folderId: z.string(),
      newParentId: z.string().nullable(),
    }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      await db.update(tuneFolders)
        .set({ parentId: input.newParentId })
        .where(and(
          eq(tuneFolders.id, input.folderId),
          eq(tuneFolders.userId, ctx.user.id),
        ));

      return { success: true };
    }),

  // Delete folder (tunes inside get folder_id set to null)
  deleteFolder: protectedProcedure
    .input(z.object({ folderId: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      // Verify ownership
      const folder = await db.select().from(tuneFolders)
        .where(and(
          eq(tuneFolders.id, input.folderId),
          eq(tuneFolders.userId, ctx.user.id),
        ));

      if (folder.length === 0) throw new Error('Folder not found');

      // Delete folder (saved_tunes.folder_id will be set to null via ON DELETE SET NULL)
      await db.delete(tuneFolders)
        .where(eq(tuneFolders.id, input.folderId));

      return { success: true };
    }),

  // Auto-generate folder hierarchy for a vehicle/ECU
  autoOrganize: protectedProcedure
    .input(z.object({
      vehicleMake: z.string(),
      vehicleModel: z.string().optional(),
      vehicleYear: z.number().optional(),
      ecuFamily: z.string().optional(),
      ecuVariant: z.string().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      const userId = ctx.user.id;
      const createdFolders: string[] = [];

      // Level 1: Make folder
      let makeFolder = await db.select().from(tuneFolders)
        .where(and(
          eq(tuneFolders.userId, userId),
          eq(tuneFolders.folderType, 'make'),
          eq(tuneFolders.vehicleMake, input.vehicleMake),
          isNull(tuneFolders.parentId),
        ));

      let makeFolderId: string;
      if (makeFolder.length === 0) {
        makeFolderId = uuidv4();
        await db.insert(tuneFolders).values({
          id: makeFolderId,
          userId,
          parentId: null,
          name: input.vehicleMake,
          folderType: 'make',
          vehicleMake: input.vehicleMake,
          isAutoGenerated: true,
        });
        createdFolders.push(makeFolderId);
      } else {
        makeFolderId = makeFolder[0].id;
      }

      // Level 2: Model folder
      let modelFolderId: string | null = null;
      if (input.vehicleModel) {
        let modelFolder = await db.select().from(tuneFolders)
          .where(and(
            eq(tuneFolders.userId, userId),
            eq(tuneFolders.folderType, 'model'),
            eq(tuneFolders.vehicleModel, input.vehicleModel),
            eq(tuneFolders.parentId, makeFolderId),
          ));

        if (modelFolder.length === 0) {
          modelFolderId = uuidv4();
          await db.insert(tuneFolders).values({
            id: modelFolderId,
            userId,
            parentId: makeFolderId,
            name: input.vehicleModel,
            folderType: 'model',
            vehicleMake: input.vehicleMake,
            vehicleModel: input.vehicleModel,
            isAutoGenerated: true,
          });
          createdFolders.push(modelFolderId);
        } else {
          modelFolderId = modelFolder[0].id;
        }
      }

      // Level 3: Year folder
      let yearFolderId: string | null = null;
      if (input.vehicleYear && modelFolderId) {
        let yearFolder = await db.select().from(tuneFolders)
          .where(and(
            eq(tuneFolders.userId, userId),
            eq(tuneFolders.folderType, 'year'),
            eq(tuneFolders.vehicleYear, input.vehicleYear),
            eq(tuneFolders.parentId, modelFolderId),
          ));

        if (yearFolder.length === 0) {
          yearFolderId = uuidv4();
          await db.insert(tuneFolders).values({
            id: yearFolderId,
            userId,
            parentId: modelFolderId,
            name: String(input.vehicleYear),
            folderType: 'year',
            vehicleMake: input.vehicleMake,
            vehicleModel: input.vehicleModel,
            vehicleYear: input.vehicleYear,
            isAutoGenerated: true,
          });
          createdFolders.push(yearFolderId);
        } else {
          yearFolderId = yearFolder[0].id;
        }
      }

      // Level 4: ECU Family folder
      let ecuFolderId: string | null = null;
      const parentForEcu = yearFolderId || modelFolderId || makeFolderId;
      if (input.ecuFamily) {
        let ecuFolder = await db.select().from(tuneFolders)
          .where(and(
            eq(tuneFolders.userId, userId),
            eq(tuneFolders.folderType, 'ecu_family'),
            eq(tuneFolders.ecuFamily, input.ecuFamily),
            eq(tuneFolders.parentId, parentForEcu),
          ));

        if (ecuFolder.length === 0) {
          ecuFolderId = uuidv4();
          await db.insert(tuneFolders).values({
            id: ecuFolderId,
            userId,
            parentId: parentForEcu,
            name: input.ecuFamily,
            folderType: 'ecu_family',
            vehicleMake: input.vehicleMake,
            vehicleModel: input.vehicleModel,
            vehicleYear: input.vehicleYear,
            ecuFamily: input.ecuFamily,
            isAutoGenerated: true,
          });
          createdFolders.push(ecuFolderId);
        } else {
          ecuFolderId = ecuFolder[0].id;
        }
      }

      // Return the deepest folder ID for placing tunes
      const targetFolderId = ecuFolderId || yearFolderId || modelFolderId || makeFolderId;

      return {
        targetFolderId,
        createdFolders,
        hierarchy: {
          make: makeFolderId,
          model: modelFolderId,
          year: yearFolderId,
          ecuFamily: ecuFolderId,
        },
      };
    }),

  // ==================== SAVED TUNES ====================

  // List tunes (optionally filtered by folder)
  listTunes: protectedProcedure
    .input(z.object({
      folderId: z.string().nullable().default(null),
      showAll: z.boolean().default(false), // show all tunes regardless of folder
      favoritesOnly: z.boolean().default(false),
    }))
    .query(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      const conditions = [eq(savedTunes.userId, ctx.user.id)];

      if (input.favoritesOnly) {
        conditions.push(eq(savedTunes.isFavorite, true));
      }

      if (!input.showAll) {
        if (input.folderId) {
          conditions.push(eq(savedTunes.folderId, input.folderId));
        } else {
          conditions.push(isNull(savedTunes.folderId));
        }
      }

      const tunes = await db.select().from(savedTunes)
        .where(and(...conditions))
        .orderBy(desc(savedTunes.updatedAt));

      return tunes;
    }),

  // Search tunes
  searchTunes: protectedProcedure
    .input(z.object({
      query: z.string().min(1),
    }))
    .query(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      const searchPattern = `%${input.query}%`;

      const tunes = await db.select().from(savedTunes)
        .where(and(
          eq(savedTunes.userId, ctx.user.id),
          or(
            like(savedTunes.name, searchPattern),
            like(savedTunes.description, searchPattern),
            like(savedTunes.vehicleMake, searchPattern),
            like(savedTunes.vehicleModel, searchPattern),
            like(savedTunes.ecuFamily, searchPattern),
            like(savedTunes.ecuPartNumber, searchPattern),
            like(savedTunes.tuneStage, searchPattern),
          ),
        ))
        .orderBy(desc(savedTunes.updatedAt))
        .limit(50);

      return tunes;
    }),

  // Save tune (with auto-organize option)
  saveTune: protectedProcedure
    .input(z.object({
      name: z.string().min(1).max(255),
      description: z.string().optional(),
      folderId: z.string().nullable().default(null),
      autoOrganize: z.boolean().default(true),
      // Vehicle / ECU metadata
      vehicleMake: z.string().optional(),
      vehicleModel: z.string().optional(),
      vehicleYear: z.number().optional(),
      ecuFamily: z.string().optional(),
      ecuId: z.string().optional(),
      osVersion: z.string().optional(),
      ecuPartNumber: z.string().optional(),
      // Tune metadata
      tuneStage: z.string().optional(),
      powerLevel: z.string().optional(),
      fuelType: z.string().optional(),
      modifications: z.string().optional(),
      notes: z.string().optional(),
      tags: z.array(z.string()).optional(),
      // File data (base64 encoded)
      binaryBase64: z.string(),
      a2lData: z.string().optional(),
      fileSize: z.number(),
      binaryHash: z.string(),
      a2lHash: z.string().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      const tuneId = uuidv4();
      let targetFolderId = input.folderId;

      // Auto-organize: create folder hierarchy if vehicle info provided
      if (input.autoOrganize && input.vehicleMake) {
        const userId = ctx.user.id;

        // Build folder hierarchy
        let makeFolderId: string | null = null;
        let modelFolderId: string | null = null;
        let yearFolderId: string | null = null;
        let ecuFolderId: string | null = null;

        // Make folder
        const existingMake = await db.select().from(tuneFolders)
          .where(and(
            eq(tuneFolders.userId, userId),
            eq(tuneFolders.folderType, 'make'),
            eq(tuneFolders.vehicleMake, input.vehicleMake),
            isNull(tuneFolders.parentId),
          ));

        if (existingMake.length > 0) {
          makeFolderId = existingMake[0].id;
        } else {
          makeFolderId = uuidv4();
          await db.insert(tuneFolders).values({
            id: makeFolderId,
            userId,
            parentId: null,
            name: input.vehicleMake,
            folderType: 'make',
            vehicleMake: input.vehicleMake,
            isAutoGenerated: true,
          });
        }

        // Model folder
        if (input.vehicleModel) {
          const existingModel = await db.select().from(tuneFolders)
            .where(and(
              eq(tuneFolders.userId, userId),
              eq(tuneFolders.folderType, 'model'),
              eq(tuneFolders.vehicleModel, input.vehicleModel),
              eq(tuneFolders.parentId, makeFolderId),
            ));

          if (existingModel.length > 0) {
            modelFolderId = existingModel[0].id;
          } else {
            modelFolderId = uuidv4();
            await db.insert(tuneFolders).values({
              id: modelFolderId,
              userId,
              parentId: makeFolderId,
              name: input.vehicleModel,
              folderType: 'model',
              vehicleMake: input.vehicleMake,
              vehicleModel: input.vehicleModel,
              isAutoGenerated: true,
            });
          }
        }

        // Year folder
        if (input.vehicleYear && modelFolderId) {
          const existingYear = await db.select().from(tuneFolders)
            .where(and(
              eq(tuneFolders.userId, userId),
              eq(tuneFolders.folderType, 'year'),
              eq(tuneFolders.vehicleYear, input.vehicleYear),
              eq(tuneFolders.parentId, modelFolderId),
            ));

          if (existingYear.length > 0) {
            yearFolderId = existingYear[0].id;
          } else {
            yearFolderId = uuidv4();
            await db.insert(tuneFolders).values({
              id: yearFolderId,
              userId,
              parentId: modelFolderId,
              name: String(input.vehicleYear),
              folderType: 'year',
              vehicleMake: input.vehicleMake,
              vehicleModel: input.vehicleModel,
              vehicleYear: input.vehicleYear,
              isAutoGenerated: true,
            });
          }
        }

        // ECU Family folder
        if (input.ecuFamily) {
          const parentForEcu = yearFolderId || modelFolderId || makeFolderId;
          const existingEcu = await db.select().from(tuneFolders)
            .where(and(
              eq(tuneFolders.userId, userId),
              eq(tuneFolders.folderType, 'ecu_family'),
              eq(tuneFolders.ecuFamily, input.ecuFamily),
              eq(tuneFolders.parentId, parentForEcu!),
            ));

          if (existingEcu.length > 0) {
            ecuFolderId = existingEcu[0].id;
          } else {
            ecuFolderId = uuidv4();
            await db.insert(tuneFolders).values({
              id: ecuFolderId,
              userId,
              parentId: parentForEcu,
              name: input.ecuFamily,
              folderType: 'ecu_family',
              vehicleMake: input.vehicleMake,
              vehicleModel: input.vehicleModel,
              vehicleYear: input.vehicleYear,
              ecuFamily: input.ecuFamily,
              isAutoGenerated: true,
            });
          }
        }

        targetFolderId = ecuFolderId || yearFolderId || modelFolderId || makeFolderId;
      }

      // Upload binary to S3 via secure broker
      const binaryBuffer = Buffer.from(input.binaryBase64, 'base64');
      const { s3Key: binaryKey, fileHash: binaryFileHash, fileSize: binaryFileSize } = await secureUpload({
        data: binaryBuffer,
        fileName: `binary-${tuneId}.bin`,
        fileType: 'binary',
        contentType: 'application/octet-stream',
        userId: ctx.user.id,
        projectId: tuneId,
      });
      const s3BinaryUrl = '[BROKERED_ACCESS]';

      // Upload A2L to S3 via secure broker if provided
      let s3A2lKey: string | undefined;
      let s3A2lUrl: string | undefined;
      if (input.a2lData) {
        const a2lBuffer = Buffer.from(input.a2lData, 'utf-8');
        const a2lResult = await secureUpload({
          data: a2lBuffer,
          fileName: `definition-${tuneId}.a2l`,
          fileType: 'a2l',
          contentType: 'text/plain',
          userId: ctx.user.id,
          projectId: tuneId,
        });
        s3A2lKey = a2lResult.s3Key;
        s3A2lUrl = '[BROKERED_ACCESS]';
      }

      // Save tune record
      await db.insert(savedTunes).values({
        id: tuneId,
        userId: ctx.user.id,
        folderId: targetFolderId,
        name: input.name,
        description: input.description,
        vehicleMake: input.vehicleMake,
        vehicleModel: input.vehicleModel,
        vehicleYear: input.vehicleYear,
        ecuFamily: input.ecuFamily,
        ecuId: input.ecuId,
        osVersion: input.osVersion,
        ecuPartNumber: input.ecuPartNumber,
        binaryHash: input.binaryHash,
        a2lHash: input.a2lHash,
        s3BinaryKey: binaryKey,
        s3BinaryUrl,
        s3A2lKey,
        s3A2lUrl,
        fileSize: input.fileSize,
        tuneStage: input.tuneStage,
        powerLevel: input.powerLevel,
        fuelType: input.fuelType,
        modifications: input.modifications,
        notes: input.notes,
        tags: input.tags ? JSON.stringify(input.tags) : null,
      });

      return {
        id: tuneId,
        folderId: targetFolderId,
        s3BinaryUrl,
        s3A2lUrl,
      };
    }),

  // Get tune details
  getTune: protectedProcedure
    .input(z.object({ tuneId: z.string() }))
    .query(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      const tune = await db.select().from(savedTunes)
        .where(and(
          eq(savedTunes.id, input.tuneId),
          eq(savedTunes.userId, ctx.user.id),
        ));

      if (tune.length === 0) throw new Error('Tune not found');
      return tune[0];
    }),

  // Update tune metadata
  updateTune: protectedProcedure
    .input(z.object({
      tuneId: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      folderId: z.string().nullable().optional(),
      tuneStage: z.string().optional(),
      powerLevel: z.string().optional(),
      fuelType: z.string().optional(),
      modifications: z.string().optional(),
      notes: z.string().optional(),
      tags: z.array(z.string()).optional(),
      isFavorite: z.boolean().optional(),
      isDispatchReady: z.boolean().optional(),
      dispatchPriority: z.number().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      const updateData: Record<string, unknown> = {};
      if (input.name !== undefined) updateData.name = input.name;
      if (input.description !== undefined) updateData.description = input.description;
      if (input.folderId !== undefined) updateData.folderId = input.folderId;
      if (input.tuneStage !== undefined) updateData.tuneStage = input.tuneStage;
      if (input.powerLevel !== undefined) updateData.powerLevel = input.powerLevel;
      if (input.fuelType !== undefined) updateData.fuelType = input.fuelType;
      if (input.modifications !== undefined) updateData.modifications = input.modifications;
      if (input.notes !== undefined) updateData.notes = input.notes;
      if (input.tags !== undefined) updateData.tags = JSON.stringify(input.tags);
      if (input.isFavorite !== undefined) updateData.isFavorite = input.isFavorite;
      if (input.isDispatchReady !== undefined) updateData.isDispatchReady = input.isDispatchReady;
      if (input.dispatchPriority !== undefined) updateData.dispatchPriority = input.dispatchPriority;

      await db.update(savedTunes)
        .set(updateData)
        .where(and(
          eq(savedTunes.id, input.tuneId),
          eq(savedTunes.userId, ctx.user.id),
        ));

      return { success: true };
    }),

  // Delete tune
  deleteTune: protectedProcedure
    .input(z.object({ tuneId: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      await db.delete(savedTunes)
        .where(and(
          eq(savedTunes.id, input.tuneId),
          eq(savedTunes.userId, ctx.user.id),
        ));

      return { success: true };
    }),

  // Toggle favorite
  toggleFavorite: protectedProcedure
    .input(z.object({ tuneId: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      const tune = await db.select().from(savedTunes)
        .where(and(
          eq(savedTunes.id, input.tuneId),
          eq(savedTunes.userId, ctx.user.id),
        ));

      if (tune.length === 0) throw new Error('Tune not found');

      await db.update(savedTunes)
        .set({ isFavorite: !tune[0].isFavorite })
        .where(eq(savedTunes.id, input.tuneId));

      return { isFavorite: !tune[0].isFavorite };
    }),

  // Move tune to folder
  moveTune: protectedProcedure
    .input(z.object({
      tuneId: z.string(),
      folderId: z.string().nullable(),
    }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error('Database not available');

      await db.update(savedTunes)
        .set({ folderId: input.folderId })
        .where(and(
          eq(savedTunes.id, input.tuneId),
          eq(savedTunes.userId, ctx.user.id),
        ));

      return { success: true };
    }),
});
