import { useState, useEffect, useCallback, useMemo } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { trpc } from '@/lib/trpc';
import { useAuth } from '@/_core/hooks/useAuth';
import { toast } from 'sonner';
import {
  Save, FolderOpen, Download, Loader2, CheckCircle, AlertCircle,
  Trash2, Star, StarOff, FolderPlus, ChevronRight, ChevronDown,
  Search, Folder, FileText, MoreVertical, Edit2, Move, Heart,
  Car, Cpu, Calendar, Tag, Zap, Fuel
} from 'lucide-react';

// ==================== TYPES ====================

interface TuneManagerProps {
  currentBinary: Uint8Array | null;
  currentA2L: string | null;
  vehicleInfo: {
    make?: string;
    model?: string;
    year?: number;
    ecuFamily?: string;
    ecuId?: string;
  };
  onTuneLoaded?: (binary: Uint8Array, a2l?: string, metadata?: any) => void;
}

interface FolderNode {
  id: string;
  name: string;
  parentId: string | null;
  folderType: string;
  vehicleMake: string | null;
  vehicleModel: string | null;
  vehicleYear: number | null;
  ecuFamily: string | null;
  isAutoGenerated: boolean | null;
  children: FolderNode[];
  tuneCount?: number;
}

// ==================== FOLDER TREE COMPONENT ====================

function FolderTree({
  folders,
  selectedFolderId,
  onSelectFolder,
  onCreateFolder,
  onDeleteFolder,
  onRenameFolder,
}: {
  folders: FolderNode[];
  selectedFolderId: string | null;
  onSelectFolder: (id: string | null) => void;
  onCreateFolder: (parentId: string | null) => void;
  onDeleteFolder: (id: string) => void;
  onRenameFolder: (id: string, name: string) => void;
}) {
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set());
  const [renamingId, setRenamingId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState('');

  const toggleExpand = (id: string) => {
    setExpandedFolders(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const startRename = (id: string, currentName: string) => {
    setRenamingId(id);
    setRenameValue(currentName);
  };

  const commitRename = () => {
    if (renamingId && renameValue.trim()) {
      onRenameFolder(renamingId, renameValue.trim());
    }
    setRenamingId(null);
  };

  const getFolderIcon = (folderType: string) => {
    switch (folderType) {
      case 'make': return <Car className="w-3.5 h-3.5 text-red-400" />;
      case 'model': return <Car className="w-3.5 h-3.5 text-orange-400" />;
      case 'year': return <Calendar className="w-3.5 h-3.5 text-yellow-400" />;
      case 'ecu_family': return <Cpu className="w-3.5 h-3.5 text-cyan-400" />;
      case 'ecu_variant': return <Cpu className="w-3.5 h-3.5 text-blue-400" />;
      default: return <Folder className="w-3.5 h-3.5 text-zinc-400" />;
    }
  };

  const renderFolder = (folder: FolderNode, depth: number = 0) => {
    const isExpanded = expandedFolders.has(folder.id);
    const isSelected = selectedFolderId === folder.id;
    const hasChildren = folder.children.length > 0;

    return (
      <div key={folder.id}>
        <div
          className={`flex items-center gap-1 py-1 px-1 rounded cursor-pointer text-[11px] transition-all group ${
            isSelected
              ? 'bg-red-500/20 text-red-300 border-l-2 border-red-500'
              : 'hover:bg-zinc-800/50 text-zinc-400 hover:text-zinc-200 border-l-2 border-transparent'
          }`}
          style={{ paddingLeft: `${depth * 12 + 4}px` }}
          onClick={() => {
            onSelectFolder(folder.id);
            if (hasChildren) toggleExpand(folder.id);
          }}
        >
          {hasChildren ? (
            isExpanded ? <ChevronDown className="w-3 h-3 shrink-0" /> : <ChevronRight className="w-3 h-3 shrink-0" />
          ) : (
            <span className="w-3 shrink-0" />
          )}

          {getFolderIcon(folder.folderType)}

          {renamingId === folder.id ? (
            <input
              value={renameValue}
              onChange={(e) => setRenameValue(e.target.value)}
              onBlur={commitRename}
              onKeyDown={(e) => { if (e.key === 'Enter') commitRename(); if (e.key === 'Escape') setRenamingId(null); }}
              className="flex-1 bg-zinc-800 border border-zinc-600 rounded px-1 text-[11px] text-zinc-200 outline-none"
              autoFocus
              onClick={(e) => e.stopPropagation()}
            />
          ) : (
            <span className="flex-1 truncate">{folder.name}</span>
          )}

          <div className="hidden group-hover:flex items-center gap-0.5">
            <button
              onClick={(e) => { e.stopPropagation(); startRename(folder.id, folder.name); }}
              className="p-0.5 hover:bg-zinc-700 rounded"
              title="Rename"
            >
              <Edit2 className="w-2.5 h-2.5" />
            </button>
            <button
              onClick={(e) => { e.stopPropagation(); onCreateFolder(folder.id); }}
              className="p-0.5 hover:bg-zinc-700 rounded"
              title="New subfolder"
            >
              <FolderPlus className="w-2.5 h-2.5" />
            </button>
            {!folder.isAutoGenerated && (
              <button
                onClick={(e) => { e.stopPropagation(); onDeleteFolder(folder.id); }}
                className="p-0.5 hover:bg-red-900/50 rounded text-red-400"
                title="Delete"
              >
                <Trash2 className="w-2.5 h-2.5" />
              </button>
            )}
          </div>
        </div>

        {isExpanded && folder.children.map(child => renderFolder(child, depth + 1))}
      </div>
    );
  };

  return (
    <div className="space-y-0.5">
      {/* Root / All Tunes */}
      <div
        className={`flex items-center gap-1.5 py-1 px-2 rounded cursor-pointer text-[11px] transition-all ${
          selectedFolderId === null
            ? 'bg-red-500/20 text-red-300 border-l-2 border-red-500'
            : 'hover:bg-zinc-800/50 text-zinc-400 hover:text-zinc-200 border-l-2 border-transparent'
        }`}
        onClick={() => onSelectFolder(null)}
      >
        <Folder className="w-3.5 h-3.5" />
        <span className="font-semibold">All Tunes</span>
      </div>

      {folders.map(folder => renderFolder(folder))}

      {/* New Root Folder button */}
      <button
        onClick={() => onCreateFolder(null)}
        className="flex items-center gap-1.5 py-1 px-2 text-[10px] text-zinc-600 hover:text-zinc-400 transition-all w-full"
      >
        <FolderPlus className="w-3 h-3" />
        New Folder
      </button>
    </div>
  );
}

// ==================== TUNE CARD COMPONENT ====================

function TuneCard({
  tune,
  onLoad,
  onDelete,
  onToggleFavorite,
  onEdit,
  isLoading,
}: {
  tune: any;
  onLoad: () => void;
  onDelete: () => void;
  onToggleFavorite: () => void;
  onEdit: () => void;
  isLoading: boolean;
}) {
  return (
    <Card className="p-3 bg-zinc-900/50 border-zinc-800 hover:border-zinc-700 transition-all group">
      <div className="flex items-start gap-2">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <h4 className="text-[12px] font-semibold text-zinc-200 truncate">{tune.name}</h4>
            {tune.isFavorite && <Star className="w-3 h-3 text-yellow-400 fill-yellow-400 shrink-0" />}
            {tune.isDispatchReady && <Zap className="w-3 h-3 text-green-400 shrink-0" />}
          </div>

          {tune.description && (
            <p className="text-[10px] text-zinc-500 truncate mt-0.5">{tune.description}</p>
          )}

          <div className="flex flex-wrap gap-x-3 gap-y-0.5 mt-1.5 text-[9px] text-zinc-500">
            {tune.vehicleMake && (
              <span className="flex items-center gap-0.5">
                <Car className="w-2.5 h-2.5" />
                {tune.vehicleMake} {tune.vehicleModel} {tune.vehicleYear}
              </span>
            )}
            {tune.ecuFamily && (
              <span className="flex items-center gap-0.5">
                <Cpu className="w-2.5 h-2.5" />
                {tune.ecuFamily}
              </span>
            )}
            {tune.tuneStage && (
              <span className="flex items-center gap-0.5">
                <Tag className="w-2.5 h-2.5" />
                {tune.tuneStage}
              </span>
            )}
            {tune.powerLevel && (
              <span className="flex items-center gap-0.5">
                <Zap className="w-2.5 h-2.5" />
                {tune.powerLevel}
              </span>
            )}
            {tune.fuelType && (
              <span className="flex items-center gap-0.5">
                <Fuel className="w-2.5 h-2.5" />
                {tune.fuelType}
              </span>
            )}
          </div>

          <div className="text-[9px] text-zinc-600 mt-1">
            {tune.fileSize ? `${(tune.fileSize / 1024 / 1024).toFixed(2)} MB` : ''} 
            {tune.updatedAt ? ` • ${new Date(tune.updatedAt).toLocaleDateString()}` : ''}
          </div>
        </div>

        <div className="flex flex-col gap-1 shrink-0">
          <Button
            size="sm"
            variant="outline"
            className="h-6 text-[9px] px-2 border-zinc-700 bg-transparent hover:bg-red-500/20 hover:border-red-500/50 hover:text-red-300"
            onClick={onLoad}
            disabled={isLoading}
          >
            {isLoading ? <Loader2 className="w-3 h-3 animate-spin" /> : <FolderOpen className="w-3 h-3" />}
          </Button>
          <button
            onClick={onToggleFavorite}
            className="p-1 hover:bg-zinc-800 rounded transition-all"
            title={tune.isFavorite ? 'Remove favorite' : 'Add favorite'}
          >
            {tune.isFavorite
              ? <Star className="w-3 h-3 text-yellow-400 fill-yellow-400" />
              : <StarOff className="w-3 h-3 text-zinc-600 hover:text-yellow-400" />
            }
          </button>
          <button
            onClick={onDelete}
            className="p-1 hover:bg-red-900/30 rounded transition-all"
            title="Delete"
          >
            <Trash2 className="w-3 h-3 text-zinc-600 hover:text-red-400" />
          </button>
        </div>
      </div>
    </Card>
  );
}

// ==================== MAIN TUNE MANAGER ====================

export function TuneManager({ currentBinary, currentA2L, vehicleInfo, onTuneLoaded }: TuneManagerProps) {
  const { user, isAuthenticated } = useAuth();
  const [activeTab, setActiveTab] = useState('save');
  const [selectedFolderId, setSelectedFolderId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [loadingTuneId, setLoadingTuneId] = useState<string | null>(null);

  // Save form state
  const [tuneName, setTuneName] = useState('');
  const [tuneDescription, setTuneDescription] = useState('');
  const [tuneStage, setTuneStage] = useState('');
  const [powerLevel, setPowerLevel] = useState('');
  const [fuelType, setFuelType] = useState('');
  const [tuneNotes, setTuneNotes] = useState('');
  const [autoOrganize, setAutoOrganize] = useState(true);
  const [savingTune, setSavingTune] = useState(false);

  // Export state
  const [exportFormat, setExportFormat] = useState<'bin' | 's' | 'hex'>('bin');

  // New folder dialog
  const [showNewFolder, setShowNewFolder] = useState(false);
  const [newFolderName, setNewFolderName] = useState('');
  const [newFolderParent, setNewFolderParent] = useState<string | null>(null);

  // Confirm delete
  const [deletingTuneId, setDeletingTuneId] = useState<string | null>(null);

  // tRPC queries
  const folderTree = trpc.tunes.getFolderTree.useQuery(undefined, {
    enabled: isAuthenticated,
  });

  const tunesList = trpc.tunes.listTunes.useQuery(
    { folderId: selectedFolderId, showAll: selectedFolderId === null },
    { enabled: isAuthenticated }
  );

  const searchResults = trpc.tunes.searchTunes.useQuery(
    { query: searchQuery },
    { enabled: isAuthenticated && searchQuery.length >= 2 }
  );

  // tRPC mutations
  const saveTuneMutation = trpc.tunes.saveTune.useMutation({
    onSuccess: () => {
      toast.success('Tune saved successfully');
      setTuneName('');
      setTuneDescription('');
      setTuneStage('');
      setPowerLevel('');
      setFuelType('');
      setTuneNotes('');
      folderTree.refetch();
      tunesList.refetch();
    },
    onError: (err) => toast.error(`Failed to save: ${err.message}`),
  });

  const createFolderMutation = trpc.tunes.createFolder.useMutation({
    onSuccess: () => {
      toast.success('Folder created');
      setShowNewFolder(false);
      setNewFolderName('');
      folderTree.refetch();
    },
    onError: (err) => toast.error(`Failed to create folder: ${err.message}`),
  });

  const renameFolderMutation = trpc.tunes.renameFolder.useMutation({
    onSuccess: () => folderTree.refetch(),
  });

  const deleteFolderMutation = trpc.tunes.deleteFolder.useMutation({
    onSuccess: () => {
      toast.success('Folder deleted');
      folderTree.refetch();
      tunesList.refetch();
    },
  });

  const deleteTuneMutation = trpc.tunes.deleteTune.useMutation({
    onSuccess: () => {
      toast.success('Tune deleted');
      setDeletingTuneId(null);
      tunesList.refetch();
    },
  });

  const toggleFavoriteMutation = trpc.tunes.toggleFavorite.useMutation({
    onSuccess: () => tunesList.refetch(),
  });

  // Build folder tree structure
  const folderTreeData = useMemo(() => {
    if (!folderTree.data) return [];

    const folderMap = new Map<string, FolderNode>();
    const roots: FolderNode[] = [];

    // Create nodes
    for (const f of folderTree.data) {
      folderMap.set(f.id, {
        id: f.id,
        name: f.name,
        parentId: f.parentId,
        folderType: f.folderType || 'custom',
        vehicleMake: f.vehicleMake,
        vehicleModel: f.vehicleModel,
        vehicleYear: f.vehicleYear,
        ecuFamily: f.ecuFamily,
        isAutoGenerated: f.isAutoGenerated,
        children: [],
      });
    }

    // Build hierarchy
    for (const f of folderTree.data) {
      const node = folderMap.get(f.id)!;
      if (f.parentId && folderMap.has(f.parentId)) {
        folderMap.get(f.parentId)!.children.push(node);
      } else {
        roots.push(node);
      }
    }

    return roots;
  }, [folderTree.data]);

  // Display tunes (search results or folder contents)
  const displayTunes = searchQuery.length >= 2 ? searchResults.data : tunesList.data;

  // ==================== HANDLERS ====================

  const handleSaveTune = async () => {
    if (!tuneName.trim()) {
      toast.error('Tune name is required');
      return;
    }
    if (!currentBinary || currentBinary.length === 0) {
      toast.error('No binary loaded to save');
      return;
    }

    setSavingTune(true);
    try {
      // Convert binary to base64
      const binaryBase64 = btoa(String.fromCharCode.apply(null, Array.from(currentBinary)));

      // Calculate hash
      const hashBuffer = await crypto.subtle.digest('SHA-256', currentBinary.buffer as ArrayBuffer);
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      const binaryHash = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');

      let a2lHash: string | undefined;
      if (currentA2L) {
        const a2lBuffer = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(currentA2L));
        a2lHash = Array.from(new Uint8Array(a2lBuffer)).map(b => b.toString(16).padStart(2, '0')).join('');
      }

      await saveTuneMutation.mutateAsync({
        name: tuneName.trim(),
        description: tuneDescription.trim() || undefined,
        folderId: autoOrganize ? null : selectedFolderId,
        autoOrganize,
        vehicleMake: vehicleInfo.make || undefined,
        vehicleModel: vehicleInfo.model || undefined,
        vehicleYear: vehicleInfo.year || undefined,
        ecuFamily: vehicleInfo.ecuFamily || undefined,
        ecuId: vehicleInfo.ecuId || undefined,
        tuneStage: tuneStage || undefined,
        powerLevel: powerLevel || undefined,
        fuelType: fuelType || undefined,
        notes: tuneNotes || undefined,
        binaryBase64,
        a2lData: currentA2L || undefined,
        fileSize: currentBinary.length,
        binaryHash,
        a2lHash,
      });
    } catch (error) {
      // Error handled by mutation onError
    } finally {
      setSavingTune(false);
    }
  };

  const handleLoadTune = async (tune: any) => {
    if (!tune.s3BinaryUrl) {
      toast.error('No binary URL available for this tune');
      return;
    }

    setLoadingTuneId(tune.id);
    try {
      // Fetch binary from S3
      const response = await fetch(tune.s3BinaryUrl);
      if (!response.ok) throw new Error('Failed to download tune binary');
      const arrayBuffer = await response.arrayBuffer();
      const binary = new Uint8Array(arrayBuffer);

      // Fetch A2L if available
      let a2l: string | undefined;
      if (tune.s3A2lUrl) {
        const a2lResponse = await fetch(tune.s3A2lUrl);
        if (a2lResponse.ok) {
          a2l = await a2lResponse.text();
        }
      }

      if (onTuneLoaded) {
        onTuneLoaded(binary, a2l, tune);
      }

      toast.success(`Loaded: ${tune.name}`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to load tune');
    } finally {
      setLoadingTuneId(null);
    }
  };

  const handleExport = () => {
    if (!currentBinary || currentBinary.length === 0) {
      toast.error('No binary loaded to export');
      return;
    }

    try {
      let data: Uint8Array | string;
      let filename: string;
      let mimeType: string;

      const baseName = tuneName || 'tune';

      switch (exportFormat) {
        case 'bin':
          data = currentBinary;
          filename = `${baseName}.bin`;
          mimeType = 'application/octet-stream';
          break;
        case 's':
          data = binaryToSRecord(currentBinary);
          filename = `${baseName}.s`;
          mimeType = 'text/plain';
          break;
        case 'hex':
          data = binaryToIntelHex(currentBinary);
          filename = `${baseName}.hex`;
          mimeType = 'text/plain';
          break;
        default:
          throw new Error('Unknown format');
      }

      const blob = new Blob([typeof data === 'string' ? data : data.buffer as ArrayBuffer], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success(`Exported: ${filename}`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Export failed');
    }
  };

  // ==================== NOT AUTHENTICATED ====================
  if (!isAuthenticated) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-6 text-center">
        <FolderOpen className="w-8 h-8 text-zinc-600 mb-3" />
        <h3 className="text-sm font-semibold text-zinc-300 mb-1">Sign In Required</h3>
        <p className="text-[10px] text-zinc-500">
          Sign in to save, organize, and manage your tunes in the cloud.
        </p>
        <p className="text-[10px] text-zinc-600 mt-2">
          Local save/export is still available below.
        </p>
        <LocalExportButton binary={currentBinary} tuneName={tuneName} />
      </div>
    );
  }

  // ==================== RENDER ====================
  return (
    <div className="flex flex-col h-full min-h-0 overflow-hidden">
      <Tabs value={activeTab} onValueChange={setActiveTab} className="flex flex-col h-full min-h-0">
        <TabsList className="shrink-0 mx-1 mt-1">
          <TabsTrigger value="save" className="text-[10px] gap-1">
            <Save className="w-3 h-3" /> Save
          </TabsTrigger>
          <TabsTrigger value="open" className="text-[10px] gap-1">
            <FolderOpen className="w-3 h-3" /> Open
          </TabsTrigger>
          <TabsTrigger value="export" className="text-[10px] gap-1">
            <Download className="w-3 h-3" /> Export
          </TabsTrigger>
        </TabsList>

        {/* ==================== SAVE TAB ==================== */}
        <TabsContent value="save" className="flex-1 overflow-auto mt-0 p-2 space-y-3">
          <div>
            <label className="block text-[10px] font-semibold text-zinc-400 mb-1 uppercase tracking-wider">Tune Name *</label>
            <Input
              placeholder="e.g., Duramax +50hp Stage 1"
              value={tuneName}
              onChange={(e) => setTuneName(e.target.value)}
              disabled={savingTune}
              className="h-7 text-[11px] bg-zinc-900 border-zinc-700"
            />
          </div>

          <div>
            <label className="block text-[10px] font-semibold text-zinc-400 mb-1 uppercase tracking-wider">Description</label>
            <Textarea
              placeholder="Notes about this tune..."
              value={tuneDescription}
              onChange={(e) => setTuneDescription(e.target.value)}
              disabled={savingTune}
              rows={2}
              className="text-[11px] bg-zinc-900 border-zinc-700 resize-none"
            />
          </div>

          {/* Tune metadata row */}
          <div className="grid grid-cols-3 gap-2">
            <div>
              <label className="block text-[9px] font-semibold text-zinc-500 mb-0.5 uppercase">Stage</label>
              <select
                value={tuneStage}
                onChange={(e) => setTuneStage(e.target.value)}
                className="w-full h-6 text-[10px] bg-zinc-900 border border-zinc-700 rounded px-1 text-zinc-300"
              >
                <option value="">—</option>
                <option value="Stock">Stock</option>
                <option value="Stage 1">Stage 1</option>
                <option value="Stage 2">Stage 2</option>
                <option value="Stage 3">Stage 3</option>
                <option value="Race">Race</option>
                <option value="Custom">Custom</option>
              </select>
            </div>
            <div>
              <label className="block text-[9px] font-semibold text-zinc-500 mb-0.5 uppercase">Power</label>
              <Input
                placeholder="+50hp"
                value={powerLevel}
                onChange={(e) => setPowerLevel(e.target.value)}
                className="h-6 text-[10px] bg-zinc-900 border-zinc-700"
              />
            </div>
            <div>
              <label className="block text-[9px] font-semibold text-zinc-500 mb-0.5 uppercase">Fuel</label>
              <select
                value={fuelType}
                onChange={(e) => setFuelType(e.target.value)}
                className="w-full h-6 text-[10px] bg-zinc-900 border border-zinc-700 rounded px-1 text-zinc-300"
              >
                <option value="">—</option>
                <option value="Diesel">Diesel</option>
                <option value="E85">E85</option>
                <option value="93 Octane">93 Octane</option>
                <option value="91 Octane">91 Octane</option>
                <option value="87 Octane">87 Octane</option>
              </select>
            </div>
          </div>

          {/* Auto-organize toggle */}
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={autoOrganize}
              onChange={(e) => setAutoOrganize(e.target.checked)}
              className="rounded border-zinc-600"
            />
            <span className="text-[10px] text-zinc-400">
              Auto-organize by vehicle/ECU
            </span>
          </label>

          {/* Vehicle info summary */}
          <div className="bg-zinc-900/50 border border-zinc-800 rounded p-2 text-[9px] text-zinc-500 space-y-0.5">
            <div><strong className="text-zinc-400">Vehicle:</strong> {vehicleInfo.make || '—'} {vehicleInfo.model || ''} {vehicleInfo.year || ''}</div>
            <div><strong className="text-zinc-400">ECU:</strong> {vehicleInfo.ecuFamily || '—'} ({vehicleInfo.ecuId || '—'})</div>
            <div><strong className="text-zinc-400">Binary:</strong> {currentBinary ? `${(currentBinary.length / 1024 / 1024).toFixed(2)} MB` : 'None loaded'}</div>
          </div>

          <Button
            onClick={handleSaveTune}
            disabled={savingTune || !currentBinary || !tuneName.trim()}
            className="w-full h-8 text-[11px] bg-red-600 hover:bg-red-700 text-white"
          >
            {savingTune ? (
              <><Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" /> Saving...</>
            ) : (
              <><Save className="w-3.5 h-3.5 mr-1.5" /> Save Tune</>
            )}
          </Button>
        </TabsContent>

        {/* ==================== OPEN TAB ==================== */}
        <TabsContent value="open" className="flex-1 overflow-hidden mt-0 flex flex-col min-h-0">
          {/* Search bar */}
          <div className="px-2 pt-2 pb-1 shrink-0">
            <div className="relative">
              <Search className="absolute left-2 top-1/2 -translate-y-1/2 w-3 h-3 text-zinc-500" />
              <Input
                placeholder="Search tunes..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="h-7 text-[11px] bg-zinc-900 border-zinc-700 pl-7"
              />
            </div>
          </div>

          <div className="flex flex-1 min-h-0 overflow-hidden">
            {/* Folder tree sidebar */}
            <div className="w-[45%] border-r border-zinc-800 overflow-auto p-1">
              <div className="text-[9px] font-bold text-zinc-600 uppercase tracking-wider px-2 mb-1">Folders</div>
              <FolderTree
                folders={folderTreeData}
                selectedFolderId={selectedFolderId}
                onSelectFolder={setSelectedFolderId}
                onCreateFolder={(parentId) => {
                  setNewFolderParent(parentId);
                  setShowNewFolder(true);
                }}
                onDeleteFolder={(id) => deleteFolderMutation.mutate({ folderId: id })}
                onRenameFolder={(id, name) => renameFolderMutation.mutate({ folderId: id, name })}
              />
            </div>

            {/* Tune list */}
            <div className="flex-1 overflow-auto p-2 space-y-1.5">
              {(tunesList.isLoading || searchResults.isLoading) ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="w-5 h-5 animate-spin text-zinc-500" />
                </div>
              ) : !displayTunes || displayTunes.length === 0 ? (
                <div className="text-center py-8 text-[11px] text-zinc-600">
                  {searchQuery.length >= 2 ? 'No tunes match your search' : 'No tunes in this folder'}
                </div>
              ) : (
                displayTunes.map((tune: any) => (
                  <TuneCard
                    key={tune.id}
                    tune={tune}
                    onLoad={() => handleLoadTune(tune)}
                    onDelete={() => setDeletingTuneId(tune.id)}
                    onToggleFavorite={() => toggleFavoriteMutation.mutate({ tuneId: tune.id })}
                    onEdit={() => {}}
                    isLoading={loadingTuneId === tune.id}
                  />
                ))
              )}
            </div>
          </div>
        </TabsContent>

        {/* ==================== EXPORT TAB ==================== */}
        <TabsContent value="export" className="flex-1 overflow-auto mt-0 p-2 space-y-3">
          <div>
            <label className="block text-[10px] font-semibold text-zinc-400 mb-1.5 uppercase tracking-wider">Export Format</label>
            <div className="space-y-1.5">
              {([
                { value: 'bin', label: 'Binary (.bin)', desc: 'Raw binary — compatible with most flashing tools' },
                { value: 's', label: 'S-Record (.s)', desc: 'Motorola S-Record — older flashing tools & bootloaders' },
                { value: 'hex', label: 'Intel HEX (.hex)', desc: 'Universal compatibility with ECU programming tools' },
              ] as const).map(({ value, label, desc }) => (
                <label
                  key={value}
                  className={`flex items-start gap-2 p-2 rounded border cursor-pointer transition-all ${
                    exportFormat === value
                      ? 'border-red-500/50 bg-red-500/10'
                      : 'border-zinc-800 hover:border-zinc-700'
                  }`}
                >
                  <input
                    type="radio"
                    value={value}
                    checked={exportFormat === value}
                    onChange={(e) => setExportFormat(e.target.value as typeof exportFormat)}
                    className="mt-0.5"
                  />
                  <div>
                    <div className="text-[11px] font-medium text-zinc-300">{label}</div>
                    <div className="text-[9px] text-zinc-500">{desc}</div>
                  </div>
                </label>
              ))}
            </div>
          </div>

          <Button
            onClick={handleExport}
            disabled={!currentBinary}
            className="w-full h-8 text-[11px] bg-red-600 hover:bg-red-700 text-white"
          >
            <Download className="w-3.5 h-3.5 mr-1.5" />
            Download to Local Device
          </Button>

          <div className="bg-amber-900/20 border border-amber-800/50 rounded p-2 text-[9px] text-amber-300/80 space-y-1">
            <p className="font-semibold">Before Flashing:</p>
            <ul className="list-disc list-inside space-y-0.5 text-amber-300/60">
              <li>Verify checksum with WinOLS or your flashing tool</li>
              <li>Ensure vehicle is in safe condition (not running)</li>
              <li>Back up original file before flashing</li>
              <li>Use appropriate flashing hardware for your ECU</li>
            </ul>
          </div>
        </TabsContent>
      </Tabs>

      {/* ==================== NEW FOLDER DIALOG ==================== */}
      <Dialog open={showNewFolder} onOpenChange={setShowNewFolder}>
        <DialogContent className="bg-zinc-900 border-zinc-700">
          <DialogHeader>
            <DialogTitle className="text-sm">New Folder</DialogTitle>
            <DialogDescription className="text-[11px]">
              Create a new folder to organize your tunes.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3">
            <Input
              placeholder="Folder name"
              value={newFolderName}
              onChange={(e) => setNewFolderName(e.target.value)}
              className="h-8 text-[11px] bg-zinc-800 border-zinc-700"
              autoFocus
              onKeyDown={(e) => {
                if (e.key === 'Enter' && newFolderName.trim()) {
                  createFolderMutation.mutate({
                    name: newFolderName.trim(),
                    parentId: newFolderParent,
                  });
                }
              }}
            />
            <Button
              onClick={() => {
                if (newFolderName.trim()) {
                  createFolderMutation.mutate({
                    name: newFolderName.trim(),
                    parentId: newFolderParent,
                  });
                }
              }}
              disabled={!newFolderName.trim() || createFolderMutation.isPending}
              className="w-full h-8 text-[11px] bg-red-600 hover:bg-red-700"
            >
              {createFolderMutation.isPending ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                'Create Folder'
              )}
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* ==================== DELETE CONFIRM DIALOG ==================== */}
      <Dialog open={!!deletingTuneId} onOpenChange={() => setDeletingTuneId(null)}>
        <DialogContent className="bg-zinc-900 border-zinc-700">
          <DialogHeader>
            <DialogTitle className="text-sm text-red-400">Delete Tune</DialogTitle>
            <DialogDescription className="text-[11px]">
              This will permanently delete this tune and its files. This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <div className="flex gap-2">
            <Button
              variant="outline"
              onClick={() => setDeletingTuneId(null)}
              className="flex-1 h-8 text-[11px] border-zinc-700 bg-transparent"
            >
              Cancel
            </Button>
            <Button
              onClick={() => {
                if (deletingTuneId) {
                  deleteTuneMutation.mutate({ tuneId: deletingTuneId });
                }
              }}
              disabled={deleteTuneMutation.isPending}
              className="flex-1 h-8 text-[11px] bg-red-600 hover:bg-red-700"
            >
              {deleteTuneMutation.isPending ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                'Delete'
              )}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// ==================== LOCAL EXPORT FALLBACK ====================

function LocalExportButton({ binary, tuneName }: { binary: Uint8Array | null; tuneName: string }) {
  if (!binary) return null;

  const handleLocalExport = () => {
    const blob = new Blob([binary.buffer as ArrayBuffer], { type: 'application/octet-stream' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${tuneName || 'tune'}.bin`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      onClick={handleLocalExport}
      variant="outline"
      size="sm"
      className="mt-4 text-[10px] border-zinc-700 bg-transparent"
    >
      <Download className="w-3 h-3 mr-1" />
      Export to Local Device
    </Button>
  );
}

// ==================== FORMAT CONVERTERS ====================

function binaryToSRecord(binary: Uint8Array): string {
  const lines: string[] = [];
  const bytesPerLine = 16;

  lines.push('S00F000068656C6C6F202020202000003C');

  for (let i = 0; i < binary.length; i += bytesPerLine) {
    const chunk = binary.slice(i, Math.min(i + bytesPerLine, binary.length));
    const address = i;
    const recordLength = chunk.length + 4;

    let record = `S3${recordLength.toString(16).padStart(2, '0').toUpperCase()}`;
    record += address.toString(16).padStart(8, '0').toUpperCase();

    for (let j = 0; j < chunk.length; j++) {
      record += chunk[j].toString(16).padStart(2, '0').toUpperCase();
    }

    const bytes: number[] = [];
    bytes.push(recordLength);
    bytes.push((address >> 24) & 0xFF);
    bytes.push((address >> 16) & 0xFF);
    bytes.push((address >> 8) & 0xFF);
    bytes.push(address & 0xFF);
    for (let j = 0; j < chunk.length; j++) bytes.push(chunk[j]);

    let sum = 0;
    for (const b of bytes) sum += b;
    record += ((~sum) & 0xFF).toString(16).padStart(2, '0').toUpperCase();

    lines.push(record);
  }

  lines.push('S70500000000FA');
  return lines.join('\n');
}

function binaryToIntelHex(binary: Uint8Array): string {
  const lines: string[] = [];
  const bytesPerLine = 16;
  let currentExtAddr = -1;

  for (let i = 0; i < binary.length; i += bytesPerLine) {
    const chunk = binary.slice(i, Math.min(i + bytesPerLine, binary.length));
    const extAddr = (i >> 16) & 0xFFFF;

    if (extAddr !== currentExtAddr) {
      currentExtAddr = extAddr;
      const elaBytes = [0x02, 0x00, 0x00, 0x04, (extAddr >> 8) & 0xFF, extAddr & 0xFF];
      let sum = 0;
      for (const b of elaBytes) sum += b;
      lines.push(`:${elaBytes.map(b => b.toString(16).padStart(2, '0')).join('')}${((-sum) & 0xFF).toString(16).padStart(2, '0')}`.toUpperCase());
    }

    const addr = i & 0xFFFF;
    const dataBytes = [chunk.length, (addr >> 8) & 0xFF, addr & 0xFF, 0x00, ...Array.from(chunk)];
    let sum = 0;
    for (const b of dataBytes) sum += b;
    lines.push(`:${dataBytes.map(b => b.toString(16).padStart(2, '0')).join('')}${((-sum) & 0xFF).toString(16).padStart(2, '0')}`.toUpperCase());
  }

  lines.push(':00000001FF');
  return lines.join('\n');
}
