CREATE TABLE `dyno_competitions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`facilityName` varchar(128),
	`city` varchar(128),
	`state` varchar(64),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`vehicleClass` varchar(64),
	`dynoType` enum('chassis','engine','hub') DEFAULT 'chassis',
	`maxParticipants` int,
	`avgTemperatureF` decimal(6,2),
	`avgBaroPressureInHg` decimal(6,3),
	`avgHumidityPct` decimal(5,2),
	`avgSaeCorrectionFactor` decimal(6,4),
	`weatherStationId` int,
	`status` enum('upcoming','active','completed','cancelled') NOT NULL DEFAULT 'upcoming',
	`createdBy` int NOT NULL,
	`startDate` timestamp,
	`endDate` timestamp,
	`participantCount` int NOT NULL DEFAULT 0,
	`runCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dyno_competitions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dyno_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`vehicleId` varchar(64),
	`vehicleName` varchar(128),
	`vehicleYear` int,
	`vehicleMake` varchar(64),
	`vehicleModel` varchar(64),
	`vehicleClass` varchar(64),
	`peakHpObserved` decimal(7,2),
	`peakTqObserved` decimal(7,2),
	`peakHpRpm` int,
	`peakTqRpm` int,
	`peakHpCorrected` decimal(7,2),
	`peakTqCorrected` decimal(7,2),
	`saeCorrectionFactor` decimal(6,4) NOT NULL,
	`temperatureF` decimal(6,2) NOT NULL,
	`baroPressureInHg` decimal(6,3) NOT NULL,
	`humidityPct` decimal(5,2),
	`densityAltitudeFt` decimal(8,1),
	`airDensityLbFt3` decimal(8,6),
	`weatherReportId` int,
	`weatherStationId` int,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`facilityName` varchar(128),
	`dynoType` enum('chassis','engine','hub') DEFAULT 'chassis',
	`dynoBrand` varchar(64),
	`competitionId` int,
	`runNumber` int DEFAULT 1,
	`notes` text,
	`dynoSheetUrl` text,
	`curveData` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dyno_sessions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `weather_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`vehicleId` varchar(64),
	`vehicleName` varchar(128),
	`latitude` decimal(10,7) NOT NULL,
	`longitude` decimal(10,7) NOT NULL,
	`city` varchar(128),
	`state` varchar(64),
	`country` varchar(64),
	`temperatureF` decimal(6,2) NOT NULL,
	`temperatureC` decimal(6,2) NOT NULL,
	`baroPressureInHg` decimal(6,3) NOT NULL,
	`baroPressureKpa` decimal(7,2) NOT NULL,
	`humidityPct` decimal(5,2),
	`altitudeFt` decimal(8,1),
	`dewPointF` decimal(6,2),
	`densityAltitudeFt` decimal(8,1),
	`airDensityLbFt3` decimal(8,6),
	`saeCorrectionFactor` decimal(6,4),
	`sensorSource` enum('obd2','j1939','kline','manual') DEFAULT 'obd2',
	`qualityScore` int DEFAULT 100,
	`measuredAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `weather_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `weather_stations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(128) NOT NULL,
	`latitude` decimal(10,7) NOT NULL,
	`longitude` decimal(10,7) NOT NULL,
	`radiusMiles` decimal(6,2) NOT NULL DEFAULT '25',
	`city` varchar(128),
	`state` varchar(64),
	`country` varchar(64),
	`avgTemperatureF` decimal(6,2),
	`avgBaroPressureInHg` decimal(6,3),
	`avgHumidityPct` decimal(5,2),
	`avgAltitudeFt` decimal(8,1),
	`avgDensityAltitudeFt` decimal(8,1),
	`avgAirDensityLbFt3` decimal(8,6),
	`avgSaeCorrectionFactor` decimal(6,4),
	`reportCount` int NOT NULL DEFAULT 0,
	`vehicleCount` int NOT NULL DEFAULT 0,
	`windowStartAt` timestamp,
	`windowEndAt` timestamp,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `weather_stations_id` PRIMARY KEY(`id`)
);
