CREATE TABLE `cloud_enrollments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`vehicleId` varchar(64),
	`vin` varchar(17),
	`vehicleYear` int,
	`vehicleMake` varchar(64),
	`vehicleModel` varchar(64),
	`vehicleEngine` varchar(64),
	`vehicleClass` varchar(64),
	`vehicleTypeKey` varchar(128) NOT NULL,
	`fleetOrgId` int,
	`isActive` boolean NOT NULL DEFAULT true,
	`shareMpg` boolean NOT NULL DEFAULT true,
	`shareHealth` boolean NOT NULL DEFAULT true,
	`sharePerformance` boolean NOT NULL DEFAULT true,
	`shareDtcs` boolean NOT NULL DEFAULT true,
	`region` varchar(64),
	`state` varchar(2),
	`enrolledAt` timestamp NOT NULL DEFAULT (now()),
	`unenrolledAt` timestamp,
	`lastReportAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cloud_enrollments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cloud_fleet_aggregates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicleTypeKey` varchar(128) NOT NULL,
	`vehicleTypeLabel` varchar(255) NOT NULL,
	`period` varchar(32) NOT NULL DEFAULT 'all-time',
	`isFleetOnly` boolean NOT NULL DEFAULT false,
	`avgMpg` decimal(6,2),
	`minMpg` decimal(6,2),
	`maxMpg` decimal(6,2),
	`medianMpg` decimal(6,2),
	`avgHealthScore` decimal(5,1),
	`avgCoolantTempF` decimal(6,1),
	`avgOilTempF` decimal(6,1),
	`avgTransTemp` decimal(6,1),
	`avgBatteryVoltage` decimal(5,2),
	`avgBoostPsi` decimal(6,1),
	`avgEgtF` decimal(7,1),
	`avgDtcCount` decimal(5,2),
	`topDtcs` text,
	`avgOdometerMiles` int,
	`minOdometerMiles` int,
	`maxOdometerMiles` int,
	`vehicleCount` int NOT NULL DEFAULT 0,
	`snapshotCount` int NOT NULL DEFAULT 0,
	`fleetVehicleCount` int NOT NULL DEFAULT 0,
	`individualVehicleCount` int NOT NULL DEFAULT 0,
	`computedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cloud_fleet_aggregates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cloud_vehicle_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`enrollmentId` int NOT NULL,
	`vehicleTypeKey` varchar(128) NOT NULL,
	`fleetOrgId` int,
	`avgMpg` decimal(6,2),
	`instantMpg` decimal(6,2),
	`totalMiles` decimal(10,1),
	`totalGallons` decimal(10,2),
	`coolantTempF` decimal(6,1),
	`oilTempF` decimal(6,1),
	`oilPressurePsi` decimal(6,1),
	`transTemp` decimal(6,1),
	`batteryVoltage` decimal(5,2),
	`boostPsi` decimal(6,1),
	`egtF` decimal(7,1),
	`fuelRailPsi` decimal(8,1),
	`airflowGps` decimal(7,2),
	`healthScore` int,
	`activeDtcCount` int DEFAULT 0,
	`activeDtcs` text,
	`odometerMiles` int,
	`ambientTempF` decimal(6,1),
	`baroPressureInHg` decimal(6,3),
	`altitudeFt` int,
	`capturedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cloud_vehicle_snapshots_id` PRIMARY KEY(`id`)
);
