CREATE TABLE `live_weather_streams` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`streamKey` varchar(64) NOT NULL,
	`title` varchar(256) NOT NULL,
	`description` text,
	`vehicleType` varchar(128),
	`callsign` varchar(64),
	`status` enum('live','paused','ended') NOT NULL DEFAULT 'live',
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`heading` decimal(5,1),
	`speedMph` decimal(6,1),
	`temperatureF` decimal(6,2),
	`baroPressureInHg` decimal(6,3),
	`humidityPct` decimal(5,2),
	`windSpeedMph` decimal(6,1),
	`windDirection` decimal(5,1),
	`engineRpm` int,
	`throttlePct` decimal(5,2),
	`engineLoadPct` decimal(5,2),
	`boostPsi` decimal(6,2),
	`transTemp` decimal(6,1),
	`coolantTemp` decimal(6,1),
	`intakeAirTemp` decimal(6,1),
	`fuelRateGph` decimal(6,2),
	`viewerCount` int NOT NULL DEFAULT 0,
	`totalDataPoints` int NOT NULL DEFAULT 0,
	`externalStreamUrl` varchar(512),
	`overlayUrl` varchar(512),
	`tags` json,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`endedAt` timestamp,
	`lastUpdateAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `live_weather_streams_id` PRIMARY KEY(`id`),
	CONSTRAINT `live_weather_streams_streamKey_unique` UNIQUE(`streamKey`)
);
--> statement-breakpoint
CREATE TABLE `stream_telemetry_points` (
	`id` int AUTO_INCREMENT NOT NULL,
	`streamId` int NOT NULL,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`heading` decimal(5,1),
	`speedMph` decimal(6,1),
	`temperatureF` decimal(6,2),
	`baroPressureInHg` decimal(6,3),
	`humidityPct` decimal(5,2),
	`windSpeedMph` decimal(6,1),
	`windDirection` decimal(5,1),
	`engineRpm` int,
	`throttlePct` decimal(5,2),
	`engineLoadPct` decimal(5,2),
	`boostPsi` decimal(6,2),
	`transTemp` decimal(6,1),
	`coolantTemp` decimal(6,1),
	`intakeAirTemp` decimal(6,1),
	`fuelRateGph` decimal(6,2),
	`capturedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stream_telemetry_points_id` PRIMARY KEY(`id`)
);
